var e=[{id:`schreiben-1`,title:`ÙÙÙØ°Ø¬ Schreiben Ø±ÙÙ 1`,description:`Ø«ÙØ§Ø« ÙÙØ§Ù ÙØªØ§Ø¨ÙØ©: Ø¨Ø±ÙØ¯ Ø¥ÙÙØªØ±ÙÙÙ ØºÙØ± Ø±Ø³ÙÙØ ÙØ´Ø§Ø±ÙØ© ÙÙØªØ¯ÙØ Ø±Ø³Ø§ÙØ© Ø±Ø³ÙÙØ©.`,tasks:[{id:`schreiben-1-1`,taskNumber:1,typeAr:`Ø¨Ø±ÙØ¯ Ø¥ÙÙØªØ±ÙÙÙ ØºÙØ± Ø±Ø³ÙÙ (Ø¥ÙÙ ØµØ¯ÙÙ)`,typeDe:`Informeller E-Mail`,wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,promptAr:`ØµØ¯ÙÙÙ Ø§ÙØ£ÙÙØ§ÙÙ "ÙÙÙØ§Ø³" ÙØ³Ø£Ù Ø¹Ù Ø§ÙØ£ÙÙ Ø§ÙØ°Ù ØªØ­Ø¨Ù. Ø§ÙØªØ¨ ÙÙ Ø¨Ø±ÙØ¯Ø§Ù ÙØµÙØ±Ø§Ù ÙØ£Ø¬Ø¨ Ø¹Ù Ø§ÙÙÙØ§Ø· Ø§ÙØªØ§ÙÙØ©:`,promptDe:`Ihr deutscher Freund Lukas fragt Sie nach Ihrem Lieblingsessen. Schreiben Sie ihm eine E-Mail.`,requirements:[`Ø§Ø°ÙØ± ÙÙØ¹ Ø·Ø¹Ø§Ù ØªØ­Ø¨Ù Ø¬Ø¯Ø§Ù ÙÙÙØ§Ø°Ø§.`,`Ø§ÙØªØ¨ Ø£ÙÙ ØªØ£ÙÙÙ Ø¹Ø§Ø¯Ø©Ù (ÙÙ Ø§ÙØ¨ÙØª Ø£Ù ÙÙ Ø§ÙÙØ·Ø¹Ù).`,`Ø§Ø³Ø£ÙÙ Ø¹Ù Ø·Ø¹Ø§ÙÙ Ø§ÙÙÙØ¶Ù.`,`Ø§ÙØªØ±Ø­ Ø£Ù ØªØ·Ø¨Ø®Ø§ ÙØ¹Ø§Ù ÙÙ ÙÙØ§ÙØ© Ø§ÙØ£Ø³Ø¨ÙØ¹.`],usefulPhrases:[{de:`Lieber Lukas, / Hallo Lukas,`,ar:`Ø¹Ø²ÙØ²Ù ÙÙÙØ§Ø³ / ÙØ±Ø­Ø¨Ø§Ù ÙÙÙØ§Ø³`},{de:`Vielen Dank fÃ¼r deine E-Mail.`,ar:`Ø´ÙØ±Ø§Ù Ø¹ÙÙ Ø¥ÙÙÙÙÙ.`},{de:`Mein Lieblingsessen ist â¦, weil â¦`,ar:`Ø£ÙÙØªÙ Ø§ÙÙÙØ¶ÙØ© ÙÙ ... ÙØ£Ù ...`},{de:`Am liebsten esse ich â¦`,ar:`Ø£Ø­Ø¨ Ø£ÙÙ ... Ø£ÙØ«Ø± Ø´ÙØ¡.`},{de:`Normalerweise esse ich zu Hause.`,ar:`Ø¹Ø§Ø¯Ø© Ø¢ÙÙ ÙÙ Ø§ÙØ¨ÙØª.`},{de:`Was isst du am liebsten?`,ar:`ÙØ§Ø°Ø§ ØªØ­Ø¨ Ø£Ù ØªØ£ÙÙØ`},{de:`Wollen wir am Samstag zusammen kochen?`,ar:`ÙÙ ÙØ·Ø¨Ø® ÙØ¹Ø§Ù ÙÙÙ Ø§ÙØ³Ø¨ØªØ`},{de:`Viele GrÃ¼Ãe / Bis bald`,ar:`ØªØ­ÙØ§ØªÙ / Ø¥ÙÙ Ø§ÙÙÙØ§Ø¡ ÙØ±ÙØ¨Ø§Ù`}],sampleAnswer:`Hallo Lukas,

vielen Dank fÃ¼r deine E-Mail! Du fragst nach meinem Lieblingsessen. Ich esse am liebsten Maqluba. Das ist ein syrisches Gericht mit Reis, HÃ¼hnerfleisch, Auberginen und Kartoffeln. Es schmeckt einfach super und erinnert mich an meine Familie.

Normalerweise esse ich zu Hause, weil meine Mutter sehr gut kocht. Ins Restaurant gehe ich nur am Wochenende.

Und was isst du am liebsten? Magst du arabisches Essen?

Ich habe eine Idee: Wollen wir am Samstag zusammen kochen? Dann zeige ich dir, wie man Maqluba macht.

Viele GrÃ¼Ãe
Samir`,sampleAnswerNotes:[`ÙÙØ§Ø­Ø¸Ø©: Ø¹Ø¯Ø¯ Ø§ÙÙÙÙØ§Øª â 90Ø ÙÙØ°Ø§ ÙÙØªØ§Ø².`,`Ø§Ø³ØªÙØ®Ø¯ÙØª ÙÙ Ø§ÙÙÙØ§Ø· Ø§ÙØ£Ø±Ø¨Ø¹ Ø§ÙÙØ·ÙÙØ¨Ø©.`,`ÙÙØ§Ø¹Ø¯ ÙÙÙÙØ¹Ø©: weil â Ø²ÙÙ Ø§ÙÙØ¶Ø§Ø±Ø¹ â ins Restaurant â Ø³Ø¤Ø§Ù ÙØ¨Ø§Ø´Ø± â Ø§ÙØªØ±Ø§Ø­ Ø¨Ø§Ø³ØªØ®Ø¯Ø§Ù "Wollen wir...?".`]},{id:`schreiben-1-2`,taskNumber:2,typeAr:`ÙØ´Ø§Ø±ÙØ© ÙÙ ÙÙØªØ¯Ù (Forum)`,typeDe:`Forumbeitrag`,wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,promptAr:`ÙØ±Ø£ØªÙ ÙØ°Ø§ Ø§ÙØ³Ø¤Ø§Ù ÙÙ ÙÙØªØ¯Ù: "ÙÙ ØªØ¹ÙÙÙ Ø§ÙØ£Ø·ÙØ§Ù ÙØºØ© Ø«Ø§ÙÙØ© ÙÙÙØ¯ Ø£Ù ÙÙØ¶Ø±ÙØ" Ø§ÙØªØ¨ Ø±Ø£ÙÙ ÙØ¹ Ø¥Ø¹Ø·Ø§Ø¡ ÙØ«Ø§Ù ÙÙ Ø­ÙØ§ØªÙ.`,promptDe:`In einem Internet-Forum finden Sie folgende Frage: âSind zwei Sprachen gut oder schlecht fÃ¼r Kinder?" Schreiben Sie Ihre Meinung.`,requirements:[`ÙØ¯ÙÙ ÙÙØ³Ù Ø¨Ø¬ÙÙØ© ÙØµÙØ±Ø©.`,`Ø§ÙØªØ¨ Ø±Ø£ÙÙ Ø¨ÙØ¶ÙØ­ (Ø¥ÙØ¬Ø§Ø¨Ù Ø£Ù Ø³ÙØ¨Ù).`,`Ø§Ø°ÙØ± Ø³Ø¨Ø¨ÙÙ Ø¹ÙÙ Ø§ÙØ£ÙÙ.`,`Ø£Ø¹Ø·Ù ÙØ«Ø§ÙØ§Ù ÙÙ Ø­ÙØ§ØªÙ Ø£Ù Ø¹Ø§Ø¦ÙØªÙ.`],usefulPhrases:[{de:`Meiner Meinung nach â¦`,ar:`ÙÙ Ø±Ø£ÙÙ ...`},{de:`Ich finde, dass â¦`,ar:`Ø£Ø±Ù Ø£Ù ...`},{de:`Einerseits â¦ andererseits â¦`,ar:`ÙÙ Ø¬ÙØ© ... ÙÙÙ Ø¬ÙØ© Ø£Ø®Ø±Ù ...`},{de:`Zum Beispiel â¦`,ar:`Ø¹ÙÙ Ø³Ø¨ÙÙ Ø§ÙÙØ«Ø§Ù ...`},{de:`Ein Vorteil ist, dass â¦`,ar:`ÙÙ Ø¥ÙØ¬Ø§Ø¨ÙØ§Øª Ø°ÙÙ Ø£Ù ...`},{de:`Zum Schluss mÃ¶chte ich sagen â¦`,ar:`ÙÙ Ø§ÙØ®ØªØ§Ù Ø£ÙØ¯Ù Ø£Ù Ø£ÙÙÙ ...`}],sampleAnswer:`Hallo zusammen,

ich heiÃe Rania und komme aus Syrien. Ich lebe seit vier Jahren in Deutschland.

Meiner Meinung nach ist es sehr gut, wenn Kinder zwei Sprachen sprechen. Erstens: Kinder lernen eine Sprache sehr schnell, besonders wenn sie jung sind. Zweitens: mit zwei Sprachen haben sie spÃ¤ter bessere Chancen im Beruf und in der Familie.

Zum Beispiel spricht mein Sohn zu Hause Arabisch mit uns, und in der Kita spricht er Deutsch. Er ist jetzt 5 Jahre alt und versteht beides sehr gut. Er hat keine Probleme.

NatÃ¼rlich muss man geduldig sein. Aber am Ende ist das ein groÃer Vorteil fÃ¼r das Kind.

Viele GrÃ¼Ãe
Rania`,sampleAnswerNotes:[`Ø¹Ø¯Ø¯ Ø§ÙÙÙÙØ§Øª â 115 (ÙÙØ¨ÙÙØ Ø§ÙØ£ÙØ¶Ù 80-120).`,`ØªÙ Ø§Ø³ØªØ®Ø¯Ø§Ù: Meiner Meinung nach â Erstens/Zweitens â Zum Beispiel â Zum Schluss.`]},{id:`schreiben-1-3`,taskNumber:3,typeAr:`Ø±Ø³Ø§ÙØ© Ø±Ø³ÙÙØ© (Ø´ÙÙÙ / Ø§Ø³ØªÙØ³Ø§Ø±)`,typeDe:`Formeller Brief / formelle E-Mail`,wordCount:`Ø­ÙØ§ÙÙ 40 ÙÙÙØ©`,promptAr:`Ø§Ø´ØªØ±ÙØª ÙØ§ØªÙØ§Ù Ø¬Ø¯ÙØ¯Ø§Ù ÙÙ ÙØªØ¬Ø± Ø¥ÙÙØªØ±ÙÙÙØ ÙÙÙÙÙ ÙØ§ ÙØ¹ÙÙ. Ø§ÙØªØ¨ Ø¨Ø±ÙØ¯Ø§Ù Ø±Ø³ÙÙØ§Ù Ø¥ÙÙ Ø®Ø¯ÙØ© Ø§ÙØ²Ø¨Ø§Ø¦Ù. ÙØ§ ØªÙØ³Ù Ø§ÙØªØ­ÙØ© Ø§ÙØ±Ø³ÙÙØ© ÙØ§ÙØ®ØªØ§Ù.`,promptDe:`Sie haben ein Handy online bestellt. Das GerÃ¤t funktioniert nicht. Schreiben Sie eine formelle E-Mail an den Kundenservice.`,requirements:[`Ø§Ø¨Ø¯Ø£ Ø¨Ù "Sehr geehrte Damen und Herren".`,`Ø§Ø°ÙØ± Ø±ÙÙ Ø§ÙØ·ÙØ¨ Ø£Ù Ø§ÙØªØ§Ø±ÙØ®.`,`Ø§Ø´Ø±Ø­ Ø§ÙÙØ´ÙÙØ© Ø¨Ø§Ø®ØªØµØ§Ø±.`,`Ø§Ø·ÙØ¨ Ø­ÙØ§Ù (Ø§Ø³ØªØ¨Ø¯Ø§Ù Ø£Ù Ø§Ø³ØªØ±Ø¬Ø§Ø¹ Ø§ÙÙØ§Ù).`,`Ø§Ø®ØªÙ Ø¨Ù "Mit freundlichen GrÃ¼Ãen".`],usefulPhrases:[{de:`Sehr geehrte Damen und Herren,`,ar:`Ø§ÙØ³ÙØ¯Ø§Øª ÙØ§ÙØ³Ø§Ø¯Ø© Ø§ÙÙØ­ØªØ±ÙÙÙØ`},{de:`Ich habe am â¦ bei Ihnen â¦ bestellt.`,ar:`ÙÙØ¯ Ø·ÙØ¨Øª ÙÙ ... ÙÙ Ø¹ÙØ¯ÙÙ ...`},{de:`Die Bestellnummer ist â¦`,ar:`Ø±ÙÙ Ø§ÙØ·ÙØ¨ ÙÙ ...`},{de:`Leider funktioniert das GerÃ¤t nicht.`,ar:`ÙÙØ£Ø³Ù Ø§ÙØ¬ÙØ§Ø² ÙØ§ ÙØ¹ÙÙ.`},{de:`Ich bitte Sie, â¦ zu tun.`,ar:`Ø£Ø±Ø¬Ù ÙÙÙÙ Ø£Ù ØªÙØ¹ÙÙØ§ ...`},{de:`Bitte antworten Sie mir bis zum â¦`,ar:`Ø£Ø±Ø¬Ù Ø§ÙØ±Ø¯Ù ÙØ¨Ù ØªØ§Ø±ÙØ® ...`},{de:`Mit freundlichen GrÃ¼Ãen`,ar:`ÙØ¹ Ø®Ø§ÙØµ Ø§ÙØªØ­ÙØ©`}],sampleAnswer:`Sehr geehrte Damen und Herren,

am 05.10. habe ich bei Ihnen ein Handy bestellt (Bestellnummer: 78245). Leider funktioniert das GerÃ¤t nicht â es lÃ¤sst sich nicht einschalten.

Ich bitte Sie, mir ein neues GerÃ¤t zu schicken oder mein Geld zurÃ¼ckzuerstatten.

Mit freundlichen GrÃ¼Ãen
Samir Al-Ahmad`,sampleAnswerNotes:[`Ø¹Ø¯Ø¯ Ø§ÙÙÙÙØ§Øª â 45 (ÙÙØªØ§Ø² ÙÙÙÙÙØ© Ø§ÙØ«Ø§ÙØ«Ø©).`,`ÙØ­ØªÙÙ ÙÙ Ø§ÙØ¹ÙØ§ØµØ± Ø§ÙØ±Ø³ÙÙØ©: Ø§ÙØªØ­ÙØ© - Ø±ÙÙ Ø§ÙØ·ÙØ¨ - Ø§ÙÙØ´ÙÙØ© - Ø§ÙØ·ÙØ¨ - Ø§ÙØ®ØªØ§Ù.`]}]},{id:`schreiben-2`,title:`ÙÙÙØ°Ø¬ Schreiben Ø±ÙÙ 2`,description:`ÙÙÙØ°Ø¬ Ø«Ø§ÙÙ ÙØ¹ ÙÙØ§Ø¶ÙØ¹ Ø§ÙÙØ¯Ø±Ø³Ø© ÙØ§ÙØ±ÙØ§Ø¶Ø© ÙØ§ÙØ¹ÙÙ.`,tasks:[{id:`schreiben-2-1`,taskNumber:1,typeAr:`Ø¨Ø±ÙØ¯ Ø¥ÙÙØªØ±ÙÙÙ Ø¥ÙÙ ØµØ¯ÙÙ`,typeDe:`Informeller E-Mail`,wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,promptAr:`ØµØ¯ÙÙØªÙ "Ø¢ÙÙØ§" Ø¯Ø¹ØªÙ ÙØ­ÙÙØ© Ø¹ÙØ¯ ÙÙÙØ§Ø¯ÙØ§ ÙÙÙ Ø§ÙØ³Ø¨Øª. Ø§ÙØªØ¨Ù ÙÙØ§ Ø¥Ø¬Ø§Ø¨Ø©.`,promptDe:`Ihre Freundin Anna hat Sie zu ihrer Geburtstagsparty am Samstag eingeladen. Antworten Sie.`,requirements:[`Ø§Ø´ÙØ±ÙÙØ§ Ø¹ÙÙ Ø§ÙØ¯Ø¹ÙØ©.`,`Ø§ÙØªØ¨Ù ÙÙ ØªØ£ØªÙÙ Ø£Ù ÙØ§Ø ÙÙÙØ§Ø°Ø§.`,`Ø§Ø³Ø£ÙÙ Ø¹Ù Ø´ÙØ¡ ÙØ¬Ø¨ Ø£Ù ØªØ­Ø¶Ø±ÙÙ.`,`Ø§ÙØªØ¨Ù ÙØ§ Ø§ÙÙØ¯ÙØ© Ø§ÙØªÙ Ø³ØªØ­Ø¶Ø±ÙÙÙØ§.`],usefulPhrases:[{de:`Danke fÃ¼r deine Einladung!`,ar:`Ø´ÙØ±Ø§Ù Ø¹ÙÙ Ø¯Ø¹ÙØªÙ!`},{de:`Ich komme gern.`,ar:`Ø³Ø¢ØªÙ Ø¨ÙÙ Ø³Ø±ÙØ±.`},{de:`Leider kann ich nicht kommen, weil â¦`,ar:`ÙÙØ£Ø³Ù ÙØ§ Ø£Ø³ØªØ·ÙØ¹ Ø§ÙÙØ¬ÙØ¡ ÙØ£Ù ...`},{de:`Soll ich etwas mitbringen?`,ar:`ÙÙ ÙØ¬Ø¨ Ø£Ù Ø£Ø­Ø¶Ø± Ø´ÙØ¦Ø§ÙØ`},{de:`Ich bringe dir â¦`,ar:`Ø³Ø£Ø­Ø¶Ø± ÙÙ ...`}],sampleAnswer:`Liebe Anna,

tausend Dank fÃ¼r deine Einladung! NatÃ¼rlich komme ich sehr gern zu deiner Geburtstagsparty am Samstag. Ich freue mich schon!

Ich wollte dich fragen: Soll ich etwas mitbringen, zum Beispiel Salat oder GetrÃ¤nke? Ich kann auch gern einen Kuchen backen, wenn du mÃ¶chtest.

Als Geschenk bekommst du ein Buch. Ich weiÃ, du liest sehr gern Krimis.

Bis Samstag!
Deine Leila`},{id:`schreiben-2-2`,taskNumber:2,typeAr:`ÙØ´Ø§Ø±ÙØ© ÙÙ Ø§ÙÙÙØªØ¯Ù`,typeDe:`Forumsbeitrag`,wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,promptAr:`ØªÙØ±Ø£ ÙÙ ÙÙØªØ¯Ù: "ÙÙ ÙØ¬Ø¨ Ø¹ÙÙ ÙÙ Ø·ÙÙ Ø£Ù ÙÙØ§Ø±Ø³ Ø±ÙØ§Ø¶Ø© ÙÙ Ø§ÙÙØ¯Ø±Ø³Ø©Ø" Ø§ÙØªØ¨ Ø±Ø£ÙÙ.`,promptDe:`Sie lesen im Forum: âSoll jedes Kind in der Schule Sport machen?" Schreiben Sie Ihre Meinung.`,requirements:[`Ø±Ø­ÙØ¨ ÙØ¹Ø±ÙÙ ÙÙØ³Ù.`,`Ø§ÙØªØ¨ Ø±Ø£ÙÙ Ø¨ÙØ¶ÙØ­.`,`Ø§Ø°ÙØ± Ø³Ø¨Ø¨ÙÙ.`,`Ø§ÙØªØ¨ Ø®ÙØ§ØµØ© ÙØµÙØ±Ø©.`],sampleAnswer:`Hallo zusammen,

ich bin Khaled, 28 Jahre alt. Meiner Meinung nach ist Sport in der Schule sehr wichtig.

Erstens bleiben die Kinder so gesund. Heutzutage sitzen Kinder zu viel vor dem Handy oder am Computer. Zweitens lernen sie durch Sport in einer Gruppe zu arbeiten und Respekt zu zeigen.

NatÃ¼rlich sollten die Lehrer verstehen, wenn ein Kind krank ist. Aber im Allgemeinen ist Sport fÃ¼r alle gut.

Viele GrÃ¼Ãe
Khaled`},{id:`schreiben-2-3`,taskNumber:3,typeAr:`Ø±Ø³Ø§ÙØ© Ø±Ø³ÙÙØ© (Ø§Ø¹ØªØ°Ø§Ø±)`,typeDe:`Formeller Brief`,wordCount:`Ø­ÙØ§ÙÙ 40 ÙÙÙØ©`,promptAr:`ÙØ¯ÙÙ ÙÙØ¹Ø¯ ØºØ¯Ø§Ù ÙÙ JobcenterØ ÙÙÙ ÙØ§ ØªØ³ØªØ·ÙØ¹ Ø§ÙØ­Ø¶ÙØ± Ø¨Ø³Ø¨Ø¨ ÙØ±Ø¶ Ø§Ø¨ÙÙ. Ø§Ø¹ØªØ°Ø± ÙØ§Ø·ÙØ¨ ÙÙØ¹Ø¯Ø§Ù Ø¬Ø¯ÙØ¯Ø§Ù.`,promptDe:`Sie haben morgen einen Termin im Jobcenter, kÃ¶nnen aber nicht kommen, weil Ihr Kind krank ist. Entschuldigen Sie sich und bitten Sie um einen neuen Termin.`,requirements:[`Ø§Ø³ØªØ¹ÙÙ Ø§ÙØªØ­ÙØ© Ø§ÙØ±Ø³ÙÙØ©.`,`Ø§Ø¹ØªØ°Ø± ÙØ§Ø°ÙØ± Ø§ÙØ³Ø¨Ø¨.`,`Ø§Ø·ÙØ¨ ÙÙØ¹Ø¯Ø§Ù Ø¬Ø¯ÙØ¯Ø§Ù ÙØ§ÙØªØ±Ø­ ÙÙØªØ§Ù.`,`Ø§Ø®ØªØªÙ Ø¨Ø´ÙÙ Ø±Ø³ÙÙ.`],sampleAnswer:`Sehr geehrte Damen und Herren,

leider kann ich morgen nicht zu meinem Termin um 10:30 Uhr kommen, weil mein Sohn plÃ¶tzlich krank geworden ist und ich zum Arzt muss.

Ich mÃ¶chte mich dafÃ¼r entschuldigen und bitte um einen neuen Termin. NÃ¤chste Woche am Dienstag oder Mittwoch wÃ¤re gut fÃ¼r mich.

Mit freundlichen GrÃ¼Ãen
Maryam Al-Hassan`}]},{id:`schreiben-3`,title:`Schreiben â ÙÙÙØ°Ø¬ 3 (Ø§ÙØ­ÙØ§Ø© Ø§ÙÙÙÙÙØ©)`,description:`Ø¯Ø¹ÙØ© ÙØ¹ÙØ¯ ÙÙÙØ§Ø¯Ø Ø±Ø£Ù ÙÙ ÙÙØ¶ÙØ¹ ØªØ¹ÙÙÙÙØ Ø´ÙÙÙ Ø±Ø³ÙÙØ©.`,tasks:[{id:`schreiben-3-1`,taskNumber:1,typeAr:`Ø¯Ø¹ÙØ© Ø´Ø®ØµÙØ© / Einladung an einen Freund`,typeDe:`E-Mail an einen Freund`,promptAr:`ØµØ¯ÙÙÙ Ø³ÙØ²ÙØ± Ø£ÙÙØ§ÙÙØ§ ÙØ£ÙÙ ÙØ±Ø©. Ø§ÙØªØ¨ ÙÙ Ø±Ø³Ø§ÙØ© ØªØ¯Ø¹ÙÙ ÙÙØ¥ÙØ§ÙØ© Ø¹ÙØ¯Ù.`,promptDe:`Ihr Freund / Ihre Freundin Kareem aus Damaskus kommt zum ersten Mal nach Deutschland zu Besuch. Schreiben Sie eine E-Mail (ca. 80 WÃ¶rter):`,requirements:[`ÙÙØ§Ø°Ø§ ÙØ±Ø­Øª Ø¨Ø±Ø³Ø§ÙØªÙØ`,`ÙØªÙ ÙØ£ØªÙ ÙÙÙ Ø³ÙØ¨ÙÙØ`,`ÙØ§Ø°Ø§ Ø³ØªÙØ¹ÙÙÙ ÙØ¹Ø§ÙØ`,`ÙØ§Ø°Ø§ ÙØ¬Ø¨ Ø£Ù ÙØ­Ø¶Ø± ÙØ¹ÙØ`],wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1527176930608-09cb256ab504?auto=format&fit=crop&w=800&q=70`,imageAlt:`Ø³ÙØ± Ø¨Ø§ÙØ·Ø§Ø¦Ø±Ø©`,usefulPhrases:[{de:`Ich freue mich riesig, dass â¦`,ar:`Ø£ÙØ§ Ø³Ø¹ÙØ¯ Ø¬Ø¯Ø§Ù Ø£Ù ...`},{de:`Du kannst gerne bei mir wohnen.`,ar:`ÙÙÙÙÙ Ø£Ù ØªØ³ÙÙ Ø¹ÙØ¯Ù.`},{de:`Bring bitte â¦ mit.`,ar:`Ø£Ø­Ø¶Ø± ÙØ¹Ù ... ÙÙ ÙØ¶ÙÙ.`},{de:`Ich hole dich vom Flughafen ab.`,ar:`Ø³Ø£ÙØ§Ø¨ÙÙ ÙÙ Ø§ÙÙØ·Ø§Ø±.`},{de:`Wir kÃ¶nnen â¦ besuchen.`,ar:`ÙÙÙÙÙØ§ Ø²ÙØ§Ø±Ø© ...`}],sampleAnswer:`Lieber Kareem,

vielen Dank fÃ¼r deine Nachricht! Ich freue mich riesig, dass du nach Deutschland kommst. Ich kann es kaum erwarten, dich endlich wiederzusehen.

Du kannst gerne bei mir wohnen. Wann genau kommst du und wie lange bleibst du? Wir kÃ¶nnen zusammen das Brandenburger Tor besuchen, in den Park gehen und natÃ¼rlich richtig deutsches Essen probieren!

Bring bitte etwas Warmes mit, denn hier ist es im Oktober schon kalt. Schick mir bitte deine Flugdaten, dann hole ich dich vom Flughafen ab.

Bis bald,
dein Ahmad`},{id:`schreiben-3-2`,taskNumber:2,typeAr:`ØªØ¹ÙÙÙ ÙÙ ÙÙÙØ¹ ØªØ¹ÙÙÙÙ`,typeDe:`Forenbeitrag`,promptAr:`ÙÙ ÙÙÙØ¹ ØªØ¹ÙÙÙÙ ÙÙØ³Ø£Ù: "ÙÙ ØªØ¹ÙÙÙ ÙØºØ© Ø¬Ø¯ÙØ¯Ø© ÙÙ Ø§ÙØ­ÙØ§Ø© Ø§ÙÙÙÙÙØ© Ø£ÙØ¶Ù ÙÙ Ø§ÙÙØ¯Ø±Ø³Ø©Ø" Ø§ÙØªØ¨ ØªØ¹ÙÙÙÙ.`,promptDe:`Auf einer Sprachlern-Seite lesen Sie die Frage: "Lernt man eine Sprache besser im Alltag als in der Schule?" Schreiben Sie Ihre Meinung (ca. 80 WÃ¶rter).`,requirements:[`ÙÙÙ ØªØ¹ÙÙÙØª Ø£ÙØª Ø§ÙØ£ÙÙØ§ÙÙØ© Ø­ØªÙ Ø§ÙØ¢ÙØ`,`ÙØ§Ø°Ø§ Ø£ÙØ¶Ù Ø¹ÙØ¯ Ø§ÙØªØ¹ÙÙ ÙÙ Ø§ÙØ­ÙØ§Ø© Ø§ÙÙÙÙÙØ©Ø`,`ÙØ§Ø°Ø§ Ø£ÙØ¶Ù Ø¹ÙØ¯ Ø§ÙØªØ¹ÙÙ ÙÙ Ø§ÙÙØ¯Ø±Ø³Ø©/Ø§ÙÙÙØ±Ø³Ø`,`ÙØ§ Ø±Ø£ÙÙ Ø£ÙØªØ ÙÙÙØ§Ø°Ø§Ø`],wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=70`,imageAlt:`ÙØªØ¨ ÙÙØ§ÙÙØ³ ÙØªØ¹ÙÙ Ø§ÙÙØºØ©`,usefulPhrases:[{de:`Meiner Meinung nach â¦`,ar:`Ø¨Ø±Ø£ÙÙ ...`},{de:`Auf der einen Seite â¦, auf der anderen Seite â¦`,ar:`ÙÙ Ø¬ÙØ© ... ÙÙÙ Ø¬ÙØ© Ø£Ø®Ø±Ù ...`},{de:`Im Alltag spricht man â¦`,ar:`ÙÙ Ø§ÙØ­ÙØ§Ø© Ø§ÙÙÙÙÙØ© ÙØªÙÙÙ Ø§ÙÙØ±Ø¡ ...`},{de:`In der Schule lernt man die Grammatik â¦`,ar:`ÙÙ Ø§ÙÙØ¯Ø±Ø³Ø© ÙØªØ¹ÙÙ Ø§ÙÙØ±Ø¡ Ø§ÙÙÙØ§Ø¹Ø¯ ...`},{de:`Ich finde es am besten, wenn man beides verbindet.`,ar:`Ø£Ø±Ù Ø£ÙÙ ÙÙ Ø§ÙØ£ÙØ¶Ù Ø¯ÙØ¬ Ø§ÙØ·Ø±ÙÙØªÙÙ.`}],sampleAnswer:`Hallo zusammen,

ich finde diese Frage sehr interessant. Ich lerne seit zwei Jahren Deutsch â im Kurs und im Alltag.

Auf der einen Seite ist die Schule wichtig: Man lernt die Grammatik, das Schreiben und die Aussprache richtig. Ohne diese Basis spricht man immer falsch.

Auf der anderen Seite ist der Alltag besser fÃ¼r das Sprechen. Man hat keine Angst, hÃ¶rt echte SÃ¤tze und kann direkt reagieren.

Meiner Meinung nach ist beides nÃ¶tig. Am besten lernt man, wenn man am Morgen einen Kurs besucht und am Nachmittag mit Deutschen spricht.`},{id:`schreiben-3-3`,taskNumber:3,typeAr:`Ø´ÙÙÙ Ø±Ø³ÙÙØ©`,typeDe:`Beschwerde-Brief`,promptAr:`Ø§Ø´ØªØ±ÙØª ØºØ³Ø§ÙØ© ÙØ¨Ù Ø£Ø³Ø¨ÙØ¹ÙÙØ ÙÙÙ ØµØ¯Ø±Øª Ø£ØµÙØ§ØªØ§Ù ØºØ±ÙØ¨Ø© ÙÙØ° ÙÙÙÙÙ. Ø§ÙØªØ¨ Ø´ÙÙÙ Ø±Ø³ÙÙØ© ÙÙÙØªØ¬Ø±.`,promptDe:`Sie haben vor zwei Wochen bei "Elektro Schmidt" eine neue Waschmaschine gekauft. Seit zwei Tagen macht sie laute GerÃ¤usche. Schreiben Sie eine Beschwerde (ca. 80 WÃ¶rter).`,requirements:[`ÙØªÙ ÙØ£ÙÙ Ø§Ø´ØªØ±ÙØª Ø§ÙØºØ³Ø§ÙØ©Ø`,`ÙØ§ ÙÙ Ø§ÙÙØ´ÙÙØ© Ø¨Ø§ÙØ¶Ø¨Ø·Ø`,`ÙØ§Ø°Ø§ ØªØ·ÙØ¨ ÙÙ Ø§ÙÙØªØ¬Ø±Ø`,`Ø­ØªÙ ÙØªÙ ØªÙØªØ¸Ø± Ø§ÙØ±Ø¯ÙØ`],wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=800&q=70`,imageAlt:`ØºØ³Ø§ÙØ© ÙÙØ±Ø¨Ø§Ø¦ÙØ©`,usefulPhrases:[{de:`Sehr geehrte Damen und Herren,`,ar:`Ø³ÙØ¯Ø§ØªÙ ÙØ³Ø§Ø¯ØªÙØ`},{de:`ich wende mich an Sie wegen â¦`,ar:`Ø£ØªÙØ¬ÙÙ Ø¥ÙÙÙÙ Ø¨Ø´Ø£Ù ...`},{de:`leider funktioniert â¦ nicht richtig.`,ar:`ÙØ³ÙØ¡ Ø§ÙØ­Ø¸ ... ÙØ§ ÙØ¹ÙÙ Ø¨Ø´ÙÙ ØµØ­ÙØ­.`},{de:`Ich bitte Sie, â¦ zu reparieren / zu erstatten.`,ar:`Ø£Ø±Ø¬Ù ÙÙÙÙ Ø£Ù ØªØµÙØ­ÙØ§ / ØªØ±Ø¯ÙÙØ§ ...`},{de:`Ich erwarte Ihre Antwort bis spÃ¤testens â¦`,ar:`Ø£ÙØªØ¸Ø± Ø±Ø¯ÙÙÙ ÙÙ ÙÙØ¹Ø¯ Ø£ÙØµØ§Ù ...`}],sampleAnswer:`Sehr geehrte Damen und Herren,

ich wende mich an Sie, weil ich am 5. MÃ¤rz in Ihrem GeschÃ¤ft "Elektro Schmidt" in DÃ¼sseldorf eine Waschmaschine der Marke Bosch gekauft habe. Die Rechnungsnummer lautet 2024-1234.

Leider macht die Maschine seit zwei Tagen sehr laute GerÃ¤usche, besonders beim Schleudern. Ich habe alles richtig angeschlossen und die Bedienungsanleitung beachtet.

Ich bitte Sie, die Waschmaschine entweder schnell zu reparieren oder mir eine neue zu liefern. Da das GerÃ¤t noch in der Garantie ist, erwarte ich keine Kosten.

Bitte antworten Sie bis spÃ¤testens nÃ¤chsten Freitag.

Mit freundlichen GrÃ¼Ãen
Mahmoud Ali`}]},{id:`schreiben-4`,title:`Schreiben â ÙÙÙØ°Ø¬ 4 (ÙÙØ§ÙÙ ÙÙÙÙØ©)`,description:`ØªØ£Ø®ÙØ± ÙÙ Ø¹ÙÙØ Ø´ÙÙÙ ÙÙ Ø¬Ø§Ø±Ø Ø±Ø¯ Ø¹ÙÙ Ø¥Ø¹ÙØ§Ù Ø´ÙØ©. ÙØ¹ ÙØµØ§Ø¦Ø­ ÙØªØ§Ø¨Ø© Ø¨Ø§ÙØ¹Ø±Ø¨ÙØ© ÙÙÙ ÙÙÙØ©.`,tasks:[{id:`schreiben-4-1`,taskNumber:1,typeAr:`Ø¨Ø±ÙØ¯ Ø±Ø³ÙÙ ÙÙÙØ¯ÙØ±: ØªØ£Ø®ÙØ± Ø¹Ù Ø§ÙØ¹ÙÙ`,typeDe:`E-Mail an den Chef`,promptAr:`ØªØ£Ø®ÙØ±Øª Ø§ÙÙÙÙ Ø¹Ù Ø¹ÙÙÙ Ø¨Ø³Ø¨Ø¨ Ø§ÙØ¨Ø§ØµØ§Øª. Ø§ÙØªØ¨ Ø¨Ø±ÙØ¯Ø§Ù ÙÙÙØ¯ÙØ± ØªØ¹ØªØ°Ø± ÙÙÙ ÙØªØ´Ø±Ø­ Ø§ÙØ³Ø¨Ø¨ ÙØªÙØªØ±Ø­ Ø­ÙØ§Ù.`,promptDe:`Schreiben Sie eine E-Mail an Ihren Chef, Herrn Becker. Heute Morgen sind Sie zur Arbeit zu spÃ¤t gekommen, weil die Busse VerspÃ¤tung hatten.`,requirements:[`Ø§Ø¹ØªØ°Ø± Ø¨Ø´ÙÙ ÙÙØ°ÙØ¨`,`Ø§Ø´Ø±Ø­ ÙØ§Ø°Ø§ Ø­Ø¯Ø«`,`Ø§ÙØªØ±Ø­ ÙÙÙ Ø³ØªØ¹ÙÙØ¶ Ø°ÙÙ`,`Ø§Ø·ÙØ¨ Ø±Ø£ÙÙ Ø£Ù ÙÙØ¹Ø¯Ø§Ù ÙÙØ­Ø¯ÙØ« ÙØ¹Ù`],wordCount:`Ø­ÙØ§ÙÙ 80-100 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=70`,imageAlt:`ÙØ­Ø·Ø© Ø¨Ø§ØµØ§Øª ÙÙ Ø§ÙØµØ¨Ø§Ø­`,usefulPhrases:[{de:`Sehr geehrter Herr â¦`,ar:`Ø­Ø¶Ø±Ø© Ø§ÙØ³ÙØ¯ Ø§ÙÙØ­ØªØ±Ù...`},{de:`Ich mÃ¶chte mich aufrichtig entschuldigen.`,ar:`Ø£Ø¹ØªØ°Ø± Ø¨ØµØ¯Ù.`},{de:`Heute Morgen hatte der Bus groÃe VerspÃ¤tung.`,ar:`Ø§ÙÙÙÙ ÙÙ Ø§ÙØµØ¨Ø§Ø­ ÙØ§Ù Ø§ÙØ¨Ø§Øµ ÙØªØ£Ø®Ø±Ø§Ù Ø¬Ø¯Ø§Ù.`},{de:`Als Ausgleich werde ich heute lÃ¤nger bleiben.`,ar:`ÙØªØ¹ÙÙØ¶ Ø³Ø£Ø¨ÙÙ Ø§ÙÙÙÙ ÙÙØ¯Ø© Ø£Ø·ÙÙ.`},{de:`Bitte teilen Sie mir mit, wann ich mit Ihnen sprechen kann.`,ar:`Ø£Ø±Ø¬Ù Ø¥Ø¹ÙØ§ÙÙ ÙØªÙ ÙÙÙÙÙÙ Ø§ÙØªØ­Ø¯Ø« ÙØ¹Ù.`},{de:`Mit freundlichen GrÃ¼Ãen`,ar:`ÙØ¹ Ø£Ø·ÙØ¨ Ø§ÙØªØ­ÙØ§Øª`}],sampleAnswerNotes:[`Ø§Ø³ØªØ®Ø¯Ù Sehr geehrter Herr Becker (ÙØ£ÙÙ Ø±Ø³ÙÙ).`,`Ø§Ø¹ØªØ°Ø± **ÙÙ Ø§ÙØ¨Ø¯Ø§ÙØ©**Ø Ø§Ø´Ø±Ø­ Ø§ÙØ³Ø¨Ø¨ Ø¨Ø¯ÙØ©Ø Ø«Ù ÙØ¯ÙÙ Ø­ÙØ§Ù.`,`ØªØ¬ÙÙØ¨ Ø§ÙØ£Ø¹Ø°Ø§Ø± Ø§ÙØ·ÙÙÙØ©. ÙÙ ÙØ§Ø¶Ø­Ø§Ù ÙÙØ®ØªØµØ±Ø§Ù.`],sampleAnswer:`Sehr geehrter Herr Becker,

ich mÃ¶chte mich aufrichtig dafÃ¼r entschuldigen, dass ich heute Morgen zu spÃ¤t zur Arbeit gekommen bin.

Der Grund war, dass mein Bus eine VerspÃ¤tung von Ã¼ber 30 Minuten hatte. Auf der Anzeigetafel stand zuerst "5 Minuten", aber dann ist der Bus einfach nicht gekommen. Auch der nÃ¤chste Bus war voll, sodass ich nicht einsteigen konnte.

Als Ausgleich werde ich heute Abend gerne lÃ¤nger bleiben oder mein Mittagspause kÃ¼rzen. In Zukunft werde ich frÃ¼her aus dem Haus gehen, damit so etwas nicht wieder passiert.

Bitte teilen Sie mir mit, wann ich mit Ihnen darÃ¼ber kurz sprechen kann.

Mit freundlichen GrÃ¼Ãen
Khaled Ahmad`},{id:`schreiben-4-2`,taskNumber:2,typeAr:`Ø¨Ø±ÙØ¯ ÙØ¬Ø§Ø±Ù: ÙØ´ÙÙØ© Ø§ÙØ¶ÙØ¶Ø§Ø¡`,typeDe:`E-Mail an den Nachbarn`,promptAr:`Ø¬Ø§Ø±Ù ÙÙ Ø§ÙØ·Ø§Ø¨Ù Ø§ÙØ¹ÙÙÙ ÙØµØ¯Ø± Ø¶ÙØ¶Ø§Ø¡ Ø¹Ø§ÙÙØ© ÙÙ Ø§ÙÙÙÙ. Ø§ÙØªØ¨ Ø±Ø³Ø§ÙØ© ÙÙØ°Ø¨Ø© ÙØªØ·ÙØ¨ ÙÙÙ Ø§ÙØªÙØ¯Ø¦Ø©.`,promptDe:`Ihr Nachbar Herr Schmidt im Stockwerk Ã¼ber Ihnen macht abends nach 22 Uhr immer sehr laute Musik. Sie kÃ¶nnen nicht schlafen.`,requirements:[`Ø­ÙÙÙÙ Ø¨Ø´ÙÙ ÙØ¯ÙØ¯`,`Ø§Ø´Ø±Ø­ Ø§ÙÙØ´ÙÙØ© Ø¨Ø¯ÙÙ Ø¥Ø³Ø§Ø¡Ø©`,`Ø§ÙØªØ±Ø­ Ø­ÙØ§Ù (Ø³Ø§Ø¹Ø§Øª ÙØ¹ÙÙØ©Ø Ø®ÙØ¶ Ø§ÙØµÙØª...)`,`Ø§Ø´ÙØ±Ù Ø¹ÙÙ ØªÙÙÙÙÙ`],wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=70`,imageAlt:`Ø¨ÙØ§ÙØ© Ø³ÙÙÙØ© ÙÙ Ø£ÙÙØ§ÙÙØ§`,usefulPhrases:[{de:`Lieber Herr / liebe Frau â¦`,ar:`Ø¹Ø²ÙØ²Ù Ø§ÙØ³ÙØ¯ / Ø¹Ø²ÙØ²ØªÙ Ø§ÙØ³ÙØ¯Ø©`},{de:`Ich wende mich an Sie, weil â¦`,ar:`Ø£ÙØªØ¨ Ø¥ÙÙÙ ÙØ£Ù...`},{de:`Es stÃ¶rt mich, wenn â¦`,ar:`ÙØ²Ø¹Ø¬ÙÙ Ø¹ÙØ¯ÙØ§...`},{de:`KÃ¶nnten Sie bitte â¦ leiser machen?`,ar:`ÙÙ ÙÙÙÙÙ Ø¬Ø¹Ù ... Ø£ÙØ¯Ø£Ø`},{de:`Vielen Dank fÃ¼r Ihr VerstÃ¤ndnis.`,ar:`Ø´ÙØ±Ø§Ù ÙØªÙÙÙÙÙ.`},{de:`Mit freundlichen GrÃ¼Ãen / Viele GrÃ¼Ãe`,ar:`ÙØ¹ Ø£Ø·ÙØ¨ Ø§ÙØªØ­ÙØ§Øª / ØªØ­ÙØ§Øª`}],sampleAnswerNotes:[`ÙÙ **ÙÙØ°Ø¨Ø§Ù Ø¬Ø¯Ø§Ù** â ÙÙ Ø£ÙÙØ§ÙÙØ§ Ø§ÙØ¬Ø§Ø± Ø¬Ø²Ø¡ ÙÙÙ ÙÙ Ø§ÙØ­ÙØ§Ø© Ø§ÙÙÙÙÙØ©.`,`ÙØ§ ØªØªÙÙÙÙ ÙØ¨Ø§Ø´Ø±Ø©. Ø§Ø³ØªØ®Ø¯Ù "ich-Form" Ø¨Ø¯Ù "Sie machen...".`,`Ø§ÙØªØ±Ø­ Ø­ÙØ§Ù ÙØ§ÙØ¹ÙØ§Ù (ÙØ«ÙØ§Ù: ØªØ®ÙÙØ¶ Ø§ÙØµÙØª Ø¨Ø¹Ø¯ Ø§ÙÙ22).`],sampleAnswer:`Lieber Herr Schmidt,

ich hoffe, es geht Ihnen gut. Ich wende mich an Sie wegen einer kleinen Sache, die mir wichtig ist.

In den letzten Wochen ist die Musik aus Ihrer Wohnung nach 22 Uhr ziemlich laut. Leider kann ich dann nicht schlafen, weil mein Schlafzimmer direkt unter Ihrem Wohnzimmer ist. Morgens muss ich um 6 Uhr aufstehen.

KÃ¶nnten Sie die Musik bitte ab 22 Uhr ein bisschen leiser machen? TagsÃ¼ber ist das natÃ¼rlich kein Problem.

Vielen Dank fÃ¼r Ihr VerstÃ¤ndnis und einen schÃ¶nen Abend!

Viele GrÃ¼Ãe
Hassan Othman (Wohnung 2A)`},{id:`schreiben-4-3`,taskNumber:3,typeAr:`Ø§Ø³ØªÙØ³Ø§Ø± Ø¹Ù Ø´ÙØ© ÙÙ Ø¥Ø¹ÙØ§Ù`,typeDe:`Anfrage zu einer Wohnung`,promptAr:`Ø±Ø£ÙØª Ø¥Ø¹ÙØ§Ù Ø´ÙØ© ÙÙ Ø§ÙØ¥ÙØªØ±ÙØª. Ø§ÙØªØ¨ Ø¨Ø±ÙØ¯Ø§Ù ÙØµØ§Ø­Ø¨ Ø§ÙØ¥Ø¹ÙØ§Ù ÙÙØ§Ø³ØªÙØ³Ø§Ø± ÙØªØ­Ø¯ÙØ¯ ÙÙØ¹Ø¯ ÙØ±Ø¤ÙØªÙØ§.`,promptDe:`Sie haben im Internet eine Anzeige fÃ¼r eine 2-Zimmer-Wohnung in MÃ¼nchen gesehen. Schreiben Sie eine E-Mail an die Vermieterin Frau Roth.`,requirements:[`Ø¹Ø±ÙÙ Ø¹Ù ÙÙØ³Ù (Ø§ÙØ§Ø³ÙØ Ø§ÙÙÙÙØ©)`,`Ø§Ø³Ø£Ù Ø£Ø³Ø¦ÙØ© ÙÙÙØ© (Ø§ÙØ¥ÙØ¬Ø§Ø±Ø Ø§ÙØªØ£Ø´ÙØ±Ø©Ø ØªØ§Ø±ÙØ® Ø§ÙØ§ÙØªÙØ§ÙØ Ø§ÙØ£Ø«Ø§Ø«)`,`Ø§Ø·ÙØ¨ ÙÙØ¹Ø¯Ø§Ù ÙÙØ¹Ø§ÙÙØ© Ø§ÙØ´ÙØ©`,`Ø§Ø´ÙØ±ÙØ§ ÙÙØ¯ÙØ¹ÙØ§ Ø¨Ø´ÙÙ Ø±Ø³ÙÙ`],wordCount:`Ø­ÙØ§ÙÙ 80-100 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=70`,imageAlt:`Ø´ÙØ© ÙØ§Ø±ØºØ© Ø¨Ø¥ÙØ¬Ø§Ø±`,usefulPhrases:[{de:`Sehr geehrte Frau Roth,`,ar:`Ø­Ø¶Ø±Ø© Ø§ÙØ³ÙØ¯Ø© Ø±ÙØª Ø§ÙÙØ­ØªØ±ÙØ©Ø`},{de:`Ich habe Ihre Anzeige im Internet gelesen.`,ar:`ÙØ±Ø£Øª Ø¥Ø¹ÙØ§ÙÙ Ø¹ÙÙ Ø§ÙØ¥ÙØªØ±ÙØª.`},{de:`Ich interessiere mich fÃ¼r die Wohnung.`,ar:`Ø£ÙØ§ ÙÙØªÙ Ø¨Ø§ÙØ´ÙØ©.`},{de:`Ich bin â¦ von Beruf.`,ar:`Ø£Ø¹ÙÙ ...`},{de:`Ist die Wohnung mÃ¶bliert?`,ar:`ÙÙ Ø§ÙØ´ÙØ© ÙÙØ±ÙØ´Ø©Ø`},{de:`Wie hoch sind die Nebenkosten?`,ar:`ÙÙ ØªØ¨ÙØº Ø§ÙØªÙØ§ÙÙÙ Ø§ÙØ¥Ø¶Ø§ÙÙØ©Ø`},{de:`Wann kÃ¶nnte ich die Wohnung besichtigen?`,ar:`ÙØªÙ ÙÙÙÙÙÙ ÙØ¹Ø§ÙÙØ© Ø§ÙØ´ÙØ©Ø`},{de:`Mit freundlichen GrÃ¼Ãen`,ar:`ÙØ¹ Ø£Ø·ÙØ¨ Ø§ÙØªØ­ÙØ§Øª`}],sampleAnswerNotes:[`ÙÙ Ø£ÙÙØ§ÙÙØ§ ÙØ§ÙÙ Ø§ÙØ´ÙØ© ÙÙØ±Ø£ **Ø¹Ø´Ø±Ø§Øª Ø§ÙØ±Ø³Ø§Ø¦Ù** ÙÙÙÙØ§Ù. ÙÙ ÙØ§Ø¶Ø­Ø§Ù ÙÙØ®ØªØµØ±Ø§Ù.`,`Ø§Ø°ÙØ± **ÙÙÙØªÙ ÙØ¯Ø®ÙÙ** â ÙÙÙ Ø¬Ø¯Ø§Ù ÙÙØ¨ÙÙÙ.`,`Ø§ÙØªØ±Ø­ **3-4 ÙÙØ§Ø¹ÙØ¯ ÙØ­Ø¯Ø¯Ø©** ÙØ²ÙØ§Ø±Ø© Ø§ÙØ´ÙØ©Ø ÙÙØ°Ø§ ÙØ³ÙÙÙ Ø§ÙÙÙØ§ÙÙØ©.`],sampleAnswer:`Sehr geehrte Frau Roth,

ich habe Ihre Anzeige fÃ¼r die 2-Zimmer-Wohnung in MÃ¼nchen-Schwabing gelesen und interessiere mich sehr dafÃ¼r.

Mein Name ist Lara Khoury. Ich bin 28 Jahre alt und arbeite als Krankenschwester in einem stÃ¤dtischen Krankenhaus mit einem festen Vertrag. Ich suche eine Wohnung ab dem 1. MÃ¤rz.

Ich habe noch ein paar Fragen:
- Ist die Wohnung mÃ¶bliert oder unmÃ¶bliert?
- Wie hoch sind die Nebenkosten ungefÃ¤hr?
- Sind Haustiere erlaubt?

KÃ¶nnte ich die Wohnung bald besichtigen? Ich habe diese Woche am Mittwoch nach 17 Uhr und am Freitag den ganzen Tag Zeit.

Vielen Dank im Voraus fÃ¼r Ihre Antwort.

Mit freundlichen GrÃ¼Ãen
Lara Khoury`}]},{id:`schreiben-5`,title:`ÙÙÙØ°Ø¬ Schreiben Ø±ÙÙ 5 (ÙÙØ· Goethe â Ø§ÙØªÙØ¸ÙÙ)`,description:`Ø«ÙØ§Ø« ÙÙØ§Ù: Ø¨Ø±ÙØ¯ ÙØ²ÙÙÙØ ÙØ´Ø§Ø±ÙØ© Ø¹Ù Ø§ÙØ¹ÙÙ Ø¹Ù Ø¨ÙØ¹Ø¯Ø Ø±Ø³Ø§ÙØ© Ø·ÙØ¨ ÙØ¸ÙÙØ©.`,tasks:[{id:`schreiben-5-1`,taskNumber:1,typeAr:`Ø¨Ø±ÙØ¯ Ø¥ÙÙØªØ±ÙÙÙ ÙØ²ÙÙÙ Ø¹ÙÙ`,typeDe:`E-Mail an Kollegen`,wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,promptAr:`Ø²ÙÙÙÙ "ÙØ§Ø±ÙÙØ³" ØºØ§Ø¨ Ø£ÙØ³ Ø¹Ù Ø§ÙØ¹ÙÙ. Ø§ÙØªØ¨ ÙÙ Ø¨Ø±ÙØ¯Ø§Ù ØªØ®Ø¨Ø±Ù ÙØ§ Ø­ØµÙ ÙØªØ³Ø£ÙÙ Ø¹Ù ØµØ­ØªÙ.`,promptDe:`Ihr Kollege Markus war gestern nicht im BÃ¼ro. Schreiben Sie ihm eine E-Mail.`,requirements:[`Ø§Ø³Ø£ÙÙ Ø¹Ù Ø³Ø¨Ø¨ ØºÙØ§Ø¨Ù ÙØ¹Ù ØµØ­ØªÙ.`,`Ø£Ø®Ø¨Ø±Ù Ø¨Ø£ÙÙ Ø´ÙØ¡ Ø­ØµÙ ÙÙ Ø§ÙØ§Ø¬ØªÙØ§Ø¹.`,`Ø§Ø¹Ø±Ø¶ Ø¹ÙÙÙ ÙØ³Ø§Ø¹Ø¯ØªÙ Ø¥Ø°Ø§ Ø§Ø­ØªØ§Ø¬.`,`Ø§ÙØªØ±Ø­ ÙÙØ¹Ø¯Ø§Ù ÙÙÙØ§Ø¡ ÙØ¨Ù Ø§Ø¬ØªÙØ§Ø¹ Ø§ÙØ¬ÙØ¹Ø©.`],usefulPhrases:[{de:`Hallo Markus,`,ar:`ÙØ±Ø­Ø¨Ø§Ù ÙØ§Ø±ÙÙØ³Ø`},{de:`wie geht es dir? Bist du krank?`,ar:`ÙÙÙ Ø­Ø§ÙÙØ ÙÙ Ø£ÙØª ÙØ±ÙØ¶Ø`},{de:`In der Sitzung gestern haben wir â¦ besprochen.`,ar:`ÙÙ Ø§Ø¬ØªÙØ§Ø¹ Ø§ÙØ£ÙØ³ ÙØ§ÙØ´ÙØ§...`},{de:`Falls du Hilfe brauchst, melde dich bei mir.`,ar:`Ø¥Ù Ø§Ø­ØªØ¬Øª ÙØ³Ø§Ø¹Ø¯Ø© ÙØ£Ø®Ø¨Ø±ÙÙ.`},{de:`KÃ¶nnen wir uns am Donnerstag kurz treffen?`,ar:`ÙÙ ÙÙØªÙÙ ÙÙÙ Ø§ÙØ®ÙÙØ³ Ø¨Ø§Ø®ØªØµØ§Ø±Ø`},{de:`Gute Besserung!`,ar:`Ø³ÙØ§ÙØªÙ / Ø´ÙØ§Ø¡ Ø¹Ø§Ø¬Ù!`}],sampleAnswer:`Hallo Markus,

ich habe gemerkt, dass du gestern nicht im BÃ¼ro warst. Ist alles in Ordnung? Bist du krank?

Im Meeting haben wir das neue Projekt mit der Firma Schmidt besprochen. Der Chef mÃ¶chte, dass wir bis Freitag einen ersten Plan vorbereiten. Falls du Hilfe brauchst, kann ich dir gerne meine Notizen schicken.

HÃ¤ttest du am Donnerstag um 14 Uhr Zeit fÃ¼r ein kurzes Treffen? So kÃ¶nnen wir uns auf Freitag vorbereiten.

Gute Besserung und bis bald!

Viele GrÃ¼Ãe
Adel`,sampleAnswerNotes:[`ÙÙ Ø§ÙÙÙØ§Ø· Ø§ÙØ£Ø±Ø¨Ø¹ ÙÙØ¬ÙØ¯Ø© Ø¨Ø´ÙÙ ÙØ§Ø¶Ø­.`,`Ø§Ø³ØªØ®Ø¯Ø§Ù Konjunktiv II Ø§ÙÙÙØ°ÙØ¨: "HÃ¤ttest du Zeit?" Ø¨Ø¯ÙØ§Ù ÙÙ "Hast du Zeit?".`,`"Gute Besserung" ØªØ¹Ø¨ÙØ± ÙØ·ÙÙ ÙØ´Ø§Ø¦Ø¹.`]},{id:`schreiben-5-2`,taskNumber:2,typeAr:`ÙØ´Ø§Ø±ÙØ© ÙÙ ÙÙØªØ¯Ù Ø¹Ù Ø§ÙØ¹ÙÙ Ø¹Ù Ø¨ÙØ¹Ø¯`,typeDe:`Forumbeitrag â Homeoffice`,wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,promptAr:`ÙØ±Ø£Øª ÙÙ ÙÙØªØ¯Ù Ø§ÙØ³Ø¤Ø§Ù Ø§ÙØªØ§ÙÙ: "ÙÙ Ø§ÙØ¹ÙÙ ÙÙ Ø§ÙØ¨ÙØª Ø£ÙØ¶Ù ÙÙ Ø§ÙØ¹ÙÙ ÙÙ Ø§ÙÙÙØªØ¨Ø" Ø§ÙØªØ¨ Ø±Ø£ÙÙ ÙØ§Ø°ÙØ± ÙØ²Ø§ÙØ§ ÙØ¹ÙÙØ¨.`,promptDe:`Lesen Sie die Frage im Forum: âIst Homeoffice besser als BÃ¼roarbeit?" Schreiben Sie Ihre Meinung.`,requirements:[`Ø§Ø°ÙØ± Ø±Ø£ÙÙ Ø¨ÙØ¶ÙØ­ ÙÙ Ø§ÙØ¨Ø¯Ø§ÙØ©.`,`Ø§Ø°ÙØ± ÙÙØ²ØªÙÙ Ø¹ÙÙ Ø§ÙØ£ÙÙ.`,`Ø§Ø°ÙØ± Ø¹ÙØ¨Ø§Ù Ø£Ù ÙØ´ÙÙØ©.`,`Ø§Ø¹Ø·Ù ÙØ«Ø§ÙØ§Ù ÙÙ ØªØ¬Ø±Ø¨ØªÙ Ø£Ù ÙÙ Ø­ÙØ§ØªÙ.`],usefulPhrases:[{de:`Liebes Forum,`,ar:`Ø¹Ø²ÙØ²Ù Ø§ÙÙÙØªØ¯ÙØ`},{de:`Meiner Meinung nach â¦`,ar:`ÙÙ Ø±Ø£ÙÙ...`},{de:`Ein groÃer Vorteil ist, dass â¦`,ar:`ÙÙ Ø£ÙØ¨Ø± Ø§ÙÙØ²Ø§ÙØ§ Ø£ÙÙ...`},{de:`Allerdings gibt es auch Nachteile.`,ar:`ØºÙØ± Ø£ÙÙ ÙÙØ§Ù Ø¹ÙÙØ¨Ø§Ù Ø£ÙØ¶Ø§Ù.`},{de:`Aus eigener Erfahrung kann ich sagen, dass â¦`,ar:`ÙÙ ØªØ¬Ø±Ø¨ØªÙ ÙÙÙÙÙÙ Ø§ÙÙÙÙ Ø¥ÙÙ...`},{de:`Zusammenfassend â¦`,ar:`Ø¨Ø§Ø®ØªØµØ§Ø±...`}],sampleAnswer:`Liebes Forum,

ich finde das Thema sehr interessant. Meiner Meinung nach hat das Homeoffice viele Vorteile.

Erstens spart man viel Zeit, weil man nicht zur Arbeit fahren muss. Zweitens kann man flexibler arbeiten und sich besser auf schwierige Aufgaben konzentrieren.

Allerdings hat das Homeoffice auch Nachteile. Man fÃ¼hlt sich oft einsam und der Kontakt zu den Kollegen geht verloren. Aus eigener Erfahrung kann ich sagen, dass mir die Mittagspause mit dem Team manchmal sehr fehlt.

Zusammenfassend finde ich eine Mischung am besten: zwei Tage zu Hause, drei Tage im BÃ¼ro.

Viele GrÃ¼Ãe,
Layla`,sampleAnswerNotes:[`Ø§Ø¨Ø¯Ø£ Ø¨Ø±Ø£Ù ÙØ§Ø¶Ø­: "ich finde das Thema interessant".`,`Ø§Ø³ØªØ®Ø¯Ù Ø§ÙØªØ±ÙÙÙ: Erstens / Zweitens / Allerdings / Zusammenfassend.`,`Ø§ÙØ­ÙÙ Ø§ÙÙØ³Ø· ÙÙ Ø§ÙÙÙØ§ÙØ© ÙØ«Ø¨Øª ÙØ¯Ø±ØªÙ Ø¹ÙÙ Ø§ÙØªÙÙÙØ± Ø§ÙÙØªÙØ§Ø²Ù.`]},{id:`schreiben-5-3`,taskNumber:3,typeAr:`Ø±Ø³Ø§ÙØ© ØªÙØ¯ÙÙ ÙÙØ¸ÙÙØ© (Ø±Ø³ÙÙ)`,typeDe:`Bewerbungsschreiben`,wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,promptAr:`ÙØ±Ø£Øª Ø¥Ø¹ÙØ§Ù ÙØ¸ÙÙØ© "Ø¨Ø§Ø¦Ø¹/Ø© ÙÙ ÙØªØ¬Ø± Ø¥ÙÙØªØ±ÙÙÙØ§Øª" Ø¹ÙÙ Ø§ÙØ¥ÙØªØ±ÙØª. Ø§ÙØªØ¨ Ø±Ø³Ø§ÙØ© ØªÙØ¯ÙÙ Ø±Ø³ÙÙØ© ØªØ°ÙØ± ÙÙÙØ§:`,promptDe:`Sie haben eine Stellenanzeige fÃ¼r âVerkÃ¤ufer/in in einem ElektronikgeschÃ¤ft" gelesen. Schreiben Sie eine Bewerbung.`,requirements:[`Ø§Ø°ÙØ± ÙØµØ¯Ø± Ø§ÙØ¥Ø¹ÙØ§Ù.`,`ÙØ¯ÙÙ ÙÙØ³Ù ÙÙÙÙØªÙ Ø§ÙØ³Ø§Ø¨ÙØ©.`,`Ø§Ø°ÙØ± Ø³Ø¨Ø¨Ø§Ù ÙØ§Ø­Ø¯Ø§Ù ÙØ¬Ø¹ÙÙ ÙÙØ§Ø³Ø¨Ø§Ù ÙÙÙØ¸ÙÙØ©.`,`Ø§Ø·ÙØ¨ ÙÙØ§Ø¨ÙØ© Ø´Ø®ØµÙØ©.`],usefulPhrases:[{de:`Sehr geehrte Damen und Herren,`,ar:`Ø­Ø¶Ø±Ø§Øª Ø§ÙØ³ÙØ¯Ø§Øª ÙØ§ÙØ³Ø§Ø¯Ø©Ø`},{de:`mit groÃem Interesse habe ich Ihre Anzeige gelesen.`,ar:`Ø¨ÙÙ Ø§ÙØªÙØ§Ù ÙØ±Ø£Øª Ø¥Ø¹ÙØ§ÙÙÙ.`},{de:`Ich bewerbe mich um die Stelle als â¦`,ar:`Ø£ØªÙØ¯Ù ÙÙØ¸ÙÙØ©...`},{de:`In meinem Heimatland habe ich als â¦ gearbeitet.`,ar:`ÙÙ Ø¨ÙØ¯Ù Ø¹ÙÙØª ÙÙ...`},{de:`Ich bin pÃ¼nktlich, freundlich und arbeite gerne im Team.`,ar:`Ø£ÙØ§ ÙÙØ¶Ø¨Ø·Ø ÙØ¯ÙØ¯ ÙØ£Ø¹ÙÙ Ø¨ÙØ±ÙÙ.`},{de:`Ich freue mich auf Ihre Antwort.`,ar:`Ø£ØªØ·ÙØ¹ ÙØ±Ø¯ÙÙ.`},{de:`Mit freundlichen GrÃ¼Ãen`,ar:`ÙØ¹ Ø£Ø·ÙØ¨ Ø§ÙØªØ­ÙØ§Øª`}],sampleAnswer:`Sehr geehrte Damen und Herren,

mit groÃem Interesse habe ich Ihre Anzeige im Internetportal "JobFinder.de" gelesen und bewerbe mich hiermit um die Stelle als VerkÃ¤ufer in Ihrem ElektronikgeschÃ¤ft.

Mein Name ist Omar Shamsi. Ich bin 28 Jahre alt und komme aus Syrien. In meinem Heimatland habe ich vier Jahre lang in einem Computer-Laden als VerkÃ¤ufer gearbeitet. Ich kenne mich daher sehr gut mit Smartphones, Laptops und ZubehÃ¶r aus.

Ich bin freundlich, geduldig und spreche Arabisch und Deutsch (B1).

Ãber die MÃ¶glichkeit eines persÃ¶nlichen GesprÃ¤chs wÃ¼rde ich mich sehr freuen.

Mit freundlichen GrÃ¼Ãen
Omar Shamsi`,sampleAnswerNotes:[`Ø§Ø³ØªØ®Ø¯Ù "mit groÃem Interesse" â ÙÙØ§Ø³Ù ÙÙ Ø·ÙØ¨Ø§Øª Ø§ÙØªÙØ¸ÙÙ.`,`Ø§Ø°ÙØ± ÙØµØ¯Ø± Ø§ÙØ¥Ø¹ÙØ§Ù Ø¨Ø¯ÙÙØ©.`,`Ø§Ø°ÙØ± Ø®Ø¨Ø±ØªÙ Ø§ÙØ³Ø§Ø¨ÙØ© ÙÙØ§ ÙÙÙÙØ²Ù (ÙØºØ§ØªØ ÙÙØ§Ø±Ø§Øª).`,`Ø§ÙÙÙ Ø¨Ø·ÙØ¨ ÙÙØ§Ø¨ÙØ© + "Mit freundlichen GrÃ¼Ãen".`]}]},{id:`schreiben-6`,title:`Schreiben â ÙÙÙØ°Ø¬ 6 (ÙÙØ§ÙÙ Ø¹Ø§Ø¦ÙÙØ© ÙØ§Ø¬ØªÙØ§Ø¹ÙØ©)`,description:`Ø¯Ø¹ÙØ© ÙØ²ÙØ§Ø¬Ø ÙÙØ§Ø´ ÙÙ ÙÙØªØ¯Ù Ø¹Ù ØªØ±Ø¨ÙØ© Ø§ÙØ£Ø·ÙØ§ÙØ Ø·ÙØ¨ ÙÙØ¹Ø¯ ÙØ¹ Ø§ÙÙØ¯Ø±ÙØ³.`,tasks:[{id:`schreiben-6-1`,taskNumber:1,typeAr:`Ø¯Ø¹ÙØ© Ø¹Ø§Ø¦ÙÙØ© (Ø¨Ø±ÙØ¯ ØºÙØ± Ø±Ø³ÙÙ)`,typeDe:`Einladung zur Hochzeit`,promptAr:`ØµØ¯ÙÙÙ Ø§ÙØ£ÙÙØ§ÙÙ Ø³ÙØªØ²ÙÙØ¬ ÙØ³Ø£ÙÙ Ø£Ù ØªØ£ØªÙ ÙØ¹Ù ÙØ¨Ù Ø§ÙØ¹Ø±Ø³ Ø¨Ø£Ø³Ø¨ÙØ¹ ÙØªØ³Ø§Ø¹Ø¯Ù. Ø§ÙØªØ¨ ÙÙ Ø¨Ø±ÙØ¯Ø§Ù.`,promptDe:`Ihr deutscher Freund Tobias heiratet bald. Er mÃ¶chte, dass Sie eine Woche vor der Hochzeit zu ihm kommen, um zu helfen. Schreiben Sie ihm eine E-Mail.`,requirements:[`Ø§Ø´ÙØ±Ù Ø¹ÙÙ Ø§ÙØ¯Ø¹ÙØ© ÙØ¹Ø¨ÙØ± Ø¹Ù Ø³Ø¹Ø§Ø¯ØªÙ`,`Ø§Ø®Ø¨Ø±Ù Ø£ÙÙ Ø³ØªØ£ØªÙ ÙØ­Ø¯ÙØ¯ ÙØªÙ`,`Ø§Ø³Ø£Ù Ø¨ÙØ§Ø°Ø§ ÙØ­ØªØ§Ø¬ Ø§ÙÙØ³Ø§Ø¹Ø¯Ø©`,`Ø§ÙØªØ±Ø­ Ø£Ù ØªØ´ØªØ±Ù ÙØ¯ÙØ© ÙØ¹Ù`],wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=70`,imageAlt:`Ø­ÙÙ Ø²ÙØ§Ù`,usefulPhrases:[{de:`Vielen Dank fÃ¼r die Einladung.`,ar:`Ø´ÙØ±Ø§Ù ÙÙØ¯Ø¹ÙØ©.`},{de:`Ich freue mich riesig fÃ¼r dich!`,ar:`Ø£ÙØ§ Ø³Ø¹ÙØ¯ Ø¬Ø¯Ø§Ù ÙÙ!`},{de:`Ich komme gerne schon eine Woche vorher.`,ar:`Ø³Ø¢ØªÙ Ø¨ÙÙ Ø³Ø±ÙØ± ÙØ¨Ù Ø£Ø³Ø¨ÙØ¹.`},{de:`Sag mir Bescheid, wo ich helfen kann.`,ar:`Ø£Ø®Ø¨Ø±ÙÙ Ø£ÙÙ ÙÙÙÙÙÙ Ø§ÙÙØ³Ø§Ø¹Ø¯Ø©.`},{de:`Sollen wir zusammen ein Geschenk besorgen?`,ar:`ÙÙ ÙØ´ØªØ±Ù ÙØ¯ÙØ© ÙØ¹Ø§ÙØ`},{de:`Liebe GrÃ¼Ãe`,ar:`ØªØ­ÙØ§ØªÙ Ø§ÙÙÙØ¨ÙØ©`}],sampleAnswerNotes:[`Ø§Ø³ØªØ®Ø¯Ù "Lieber Tobias" ÙØ£ÙÙ ØµØ¯ÙÙ.`,`Ø§Ø­Ø±Øµ Ø¹ÙÙ Ø°ÙØ± Ø§ÙØªØ§Ø±ÙØ® Ø¨Ø¯ÙÙØ© ÙÙÙÙ Ø³ØªØµÙ Ø¥ÙÙÙ.`,`ÙÙ Ø¯Ø§ÙØ¦Ø§Ù ÙØ¹ÙÙÙØ§Ù â ÙØ°Ø§ Ø¨Ø±ÙØ¯ ØºÙØ± Ø±Ø³ÙÙ.`],sampleAnswer:`Lieber Tobias,

vielen Dank fÃ¼r deine Einladung â ich freue mich riesig fÃ¼r dich und Anna! NatÃ¼rlich komme ich gerne schon eine Woche vorher und helfe euch bei den Vorbereitungen.

Ich plane, am Samstag, den 15. Juni, mit dem Zug anzukommen. Sag mir bitte Bescheid, ob das passt und wo ich genau helfen kann â Einladungen verschicken, Saal dekorieren oder vielleicht beim Essen?

AuÃerdem mÃ¶chte ich ein gemeinsames Geschenk mit dir besorgen, falls du noch Ideen hast. Was meinst du?

Bis bald, mein Freund!

Liebe GrÃ¼Ãe,
Omar`},{id:`schreiben-6-2`,taskNumber:2,typeAr:`ÙÙØªØ¯Ù: ÙÙØ§Ø´ Ø¹Ù ØªØ±Ø¨ÙØ© Ø§ÙØ£Ø·ÙØ§Ù ÙØ§ÙØ´Ø§Ø´Ø§Øª`,typeDe:`Forumbeitrag`,promptAr:`ÙÙ ÙÙØªØ¯Ù ÙÙØ¢Ø¨Ø§Ø¡Ø Ø£Ø­Ø¯ÙÙ ÙØªØ¨: "Ø£ÙØ§ Ø¶Ø¯ Ø¥Ø¹Ø·Ø§Ø¡ Ø§ÙÙÙØ§ØªÙ ÙÙØ£Ø·ÙØ§Ù ÙØ¨Ù Ø³Ù 14". Ø§ÙØªØ¨ Ø±Ø£ÙÙ.`,promptDe:`In einem Forum schreibt ein Vater: "Kinder unter 14 sollten kein Handy haben." Schreiben Sie Ihren Beitrag dazu.`,requirements:[`Ø¹Ø¨ÙØ± Ø¹Ù Ø±Ø£ÙÙ Ø¨ÙØ¶ÙØ­ (ÙÙØ§ÙÙ/Ø¶Ø¯)`,`ÙØ¯ÙÙ Ø³Ø¨Ø¨ÙÙ Ø¹ÙÙ Ø§ÙØ£ÙÙ`,`Ø§Ø°ÙØ± ØªØ¬Ø±Ø¨ØªÙ Ø£Ù ØªØ¬Ø±Ø¨Ø© Ø´Ø®Øµ ØªØ¹Ø±ÙÙ`,`Ø§ÙØªØ±Ø­ Ø­ÙØ§Ù ÙØ³Ø·Ø§Ù`],wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,usefulPhrases:[{de:`Meiner Meinung nach â¦`,ar:`Ø¨Ø±Ø£ÙÙ ...`},{de:`Ich stimme dem nicht ganz zu.`,ar:`ÙØ§ Ø£ÙØ§ÙÙ ØªÙØ§ÙØ§Ù.`},{de:`Auf der einen Seite â¦ auf der anderen Seite â¦`,ar:`ÙÙ ÙØ§Ø­ÙØ©... ÙÙÙ ÙØ§Ø­ÙØ© Ø£Ø®Ø±Ù...`},{de:`In meiner Familie â¦`,ar:`ÙÙ Ø¹Ø§Ø¦ÙØªÙ ...`},{de:`Ein Kompromiss wÃ¤re â¦`,ar:`Ø§ÙØ­Ù Ø§ÙÙØ³Ø· ÙÙ ...`},{de:`Wichtig finde ich, dass die Eltern Regeln aufstellen.`,ar:`Ø£Ø±Ù Ø£ÙÙ ÙÙ Ø§ÙÙÙÙ Ø£Ù ÙØ¶Ø¹ Ø§ÙØ£ÙÙ ÙÙØ§Ø¹Ø¯.`}],sampleAnswerNotes:[`Ø§ÙØªØ­ Ø¨Ø±Ø£ÙÙ ÙØ¨Ø§Ø´Ø±Ø© (Ich finde / Meiner Meinung nach).`,`Ø§Ø³ØªØ®Ø¯Ù Konnektoren: auÃerdem, jedoch, deshalb.`,`Ø§Ø°ÙØ± ÙØ«Ø§ÙØ§Ù Ø­ÙÙÙÙØ§Ù = Ø¯Ø±Ø¬Ø© Ø¥Ø¶Ø§ÙÙØ©.`],sampleAnswer:`Meiner Meinung nach ist diese Regel zu streng. Ein totales Verbot bis 14 finde ich nicht realistisch, weil heute fast alle Klassenkameraden ein Handy haben.

Auf der anderen Seite verstehe ich die Sorge der Eltern. Soziale Medien kÃ¶nnen Kinder unter Druck setzen, und manche verbringen zu viel Zeit am Bildschirm.

Bei uns zu Hause hat meine Tochter (12) ein einfaches Handy ohne Internet. Sie kann uns anrufen, aber spielt nicht stundenlang. Das funktioniert sehr gut.

Ein Kompromiss wÃ¤re also: ein Handy mit klaren Regeln, statt eines kompletten Verbots.`},{id:`schreiben-6-3`,taskNumber:3,typeAr:`Ø¨Ø±ÙØ¯ Ø±Ø³ÙÙ ÙÙÙØ¯Ø±ÙØ³: Ø·ÙØ¨ ÙÙØ¹Ø¯ ÙÙÙØ§ÙØ´Ø© Ø¯Ø±Ø¬Ø§Øª Ø§ÙØ§Ø¨Ù`,typeDe:`E-Mail an den Lehrer`,promptAr:`Ø§Ø¨ÙÙ ÙÙ Ø§ÙÙØ¯Ø±Ø³Ø©Ø Ø­ØµÙ Ø¹ÙÙ Ø¯Ø±Ø¬Ø§Øª Ø³ÙØ¦Ø© ÙÙ Ø§ÙØ±ÙØ§Ø¶ÙØ§Øª. Ø§ÙØªØ¨ Ø¨Ø±ÙØ¯Ø§Ù ÙÙÙØ¯Ø±ÙØ³ ØªØ·ÙØ¨ ÙÙÙ ÙÙØ¹Ø¯Ø§Ù ÙÙÙØ§Ø¡.`,promptDe:`Ihr Sohn hat schlechte Noten in Mathematik bekommen. Schreiben Sie eine E-Mail an den Klassenlehrer, Herrn MÃ¼ller, und bitten Sie um einen Termin.`,requirements:[`Ø­ÙÙÙ Ø§ÙÙØ¯Ø±ÙØ³ Ø¨Ø´ÙÙ Ø±Ø³ÙÙ`,`Ø§Ø´Ø±Ø­ Ø³Ø¨Ø¨ Ø§ÙØ¨Ø±ÙØ¯ (Ø§ÙØ¯Ø±Ø¬Ø§Øª)`,`Ø§Ø·ÙØ¨ ÙÙØ¹Ø¯Ø§Ù ÙÙÙØ§Ø¡ ÙØ­Ø¯ÙØ¯ ÙÙØªÙ Ø§ÙÙØªØ§Ø­`,`Ø§Ø·ÙØ¨ ÙØµÙØ­Ø© ÙÙØ³Ø§Ø¹Ø¯Ø© Ø§Ø¨ÙÙ ÙÙ Ø§ÙØ¨ÙØª`],wordCount:`Ø­ÙØ§ÙÙ 80-100 ÙÙÙØ©`,usefulPhrases:[{de:`Sehr geehrter Herr MÃ¼ller,`,ar:`Ø­Ø¶Ø±Ø© Ø§ÙØ³ÙØ¯ ÙÙÙØ± Ø§ÙÙØ­ØªØ±ÙØ`},{de:`mit Sorge habe ich die letzten Noten meines Sohnes gesehen.`,ar:`Ø¨ÙÙÙ ÙØ§Ø­Ø¸ØªÙ Ø¯Ø±Ø¬Ø§Øª Ø§Ø¨ÙÙ Ø§ÙØ£Ø®ÙØ±Ø©.`},{de:`Ich mÃ¶chte gerne mit Ihnen sprechen.`,ar:`Ø£ÙØ¯Ù Ø§ÙØªØ­Ø¯ÙØ« ÙØ¹Ù.`},{de:`HÃ¤tten Sie nÃ¤chste Woche Zeit fÃ¼r ein GesprÃ¤ch?`,ar:`ÙÙ ÙØ¯ÙÙ ÙÙØª Ø§ÙØ£Ø³Ø¨ÙØ¹ Ø§ÙÙØ§Ø¯Ù ÙÙØ­Ø§Ø¯Ø«Ø©Ø`},{de:`Wie kann ich ihn zu Hause unterstÃ¼tzen?`,ar:`ÙÙÙ Ø£Ø³ØªØ·ÙØ¹ Ø¯Ø¹ÙÙ ÙÙ Ø§ÙØ¨ÙØªØ`},{de:`Mit freundlichen GrÃ¼Ãen`,ar:`ÙØ¹ Ø£Ø·ÙØ¨ Ø§ÙØªØ­ÙØ§Øª`}],sampleAnswerNotes:[`Ø§ÙØªØ­ Ø¨Ù Sehr geehrter Herr MÃ¼ller.`,`Ø§Ø¸ÙØ± Ø§ÙØªÙØ§ÙÙ (mit Sorge / es liegt mir am Herzen).`,`ÙÙ ÙØ±ÙØ§Ù ÙÙ Ø§ÙØªØ±Ø§Ø­ Ø§ÙÙÙØ¹Ø¯.`],sampleAnswer:`Sehr geehrter Herr MÃ¼ller,

mit Sorge habe ich gesehen, dass mein Sohn Karim in Mathematik in letzter Zeit deutlich schlechtere Noten bekommen hat. Da mir seine Schullaufbahn sehr wichtig ist, mÃ¶chte ich gerne mit Ihnen Ã¼ber die Situation sprechen.

HÃ¤tten Sie nÃ¤chste Woche Zeit fÃ¼r ein kurzes GesprÃ¤ch? Ich kann am Mittwoch oder Donnerstag nach 15 Uhr in die Schule kommen, andere Tage sind aber auch mÃ¶glich.

AuÃerdem wÃ¼rde ich mich freuen zu erfahren, wie ich Karim zu Hause besser unterstÃ¼tzen kann â vielleicht mit zusÃ¤tzlichen Ãbungen oder einem Nachhilfelehrer.

Vielen Dank im Voraus fÃ¼r Ihre Zeit.

Mit freundlichen GrÃ¼Ãen
Yusuf Haddad`}]},{id:`schreiben-7`,title:`Schreiben â ÙÙÙØ°Ø¬ 7 (Ø§ÙØ¥Ø¯Ø§Ø±Ø© ÙØ§ÙÙÙØ§ØªØ¨ Ø§ÙØ±Ø³ÙÙØ©)`,description:`ØªÙØ§ØµÙ ÙØ¹ KrankenkasseØ Ø´ÙÙÙ ÙØ§ÙÙØ© ÙÙ JobcenterØ Ø§Ø³ØªÙØ³Ø§Ø± ÙÙ BÃ¼rgeramt â ÙÙÙ Ø¬Ø¯Ø§Ù ÙÙØ³ÙØ±ÙÙÙ.`,tasks:[{id:`schreiben-7-1`,taskNumber:1,typeAr:`Ø¨Ø±ÙØ¯ Ø±Ø³ÙÙ ÙÙØªØ£ÙÙÙ Ø§ÙØµØ­Ù: ØªØºÙÙØ± Ø§ÙØ¹ÙÙØ§Ù`,typeDe:`E-Mail an die Krankenkasse`,promptAr:`Ø§ÙØªÙÙØª Ø¥ÙÙ Ø´ÙØ© Ø¬Ø¯ÙØ¯Ø©. Ø§ÙØªØ¨ ÙÙØªØ£ÙÙÙ Ø§ÙØµØ­Ù (AOK) ÙØ¥Ø¨ÙØ§ØºÙÙ Ø¨Ø§ÙØ¹ÙÙØ§Ù Ø§ÙØ¬Ø¯ÙØ¯.`,promptDe:`Sie sind in eine neue Wohnung umgezogen. Schreiben Sie eine E-Mail an Ihre Krankenkasse (AOK), um Ihre neue Adresse mitzuteilen.`,requirements:[`Ø§Ø°ÙØ± Ø§Ø³ÙÙ ÙØ±ÙÙ ØªØ£ÙÙÙÙ`,`Ø§Ø°ÙØ± Ø§ÙØ¹ÙÙØ§Ù Ø§ÙÙØ¯ÙÙ ÙØ§ÙØ¬Ø¯ÙØ¯`,`Ø§Ø·ÙØ¨ ØªØ£ÙÙØ¯ Ø§Ø³ØªÙØ§Ù Ø§ÙØ¨Ø±ÙØ¯`,`Ø§Ø³Ø£Ù Ø¥Ø°Ø§ ÙØ§ÙØª Ø¨Ø·Ø§ÙØ© Ø¬Ø¯ÙØ¯Ø© Ø¶Ø±ÙØ±ÙØ©`],wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,usefulPhrases:[{de:`Sehr geehrte Damen und Herren,`,ar:`Ø³ÙØ¯Ø§ØªÙ Ø³Ø§Ø¯ØªÙ Ø§ÙÙØ­ØªØ±ÙÙÙØ`},{de:`hiermit teile ich Ihnen meine neue Adresse mit.`,ar:`Ø¨ÙØ°Ø§ Ø£Ø¹ÙÙÙÙ Ø¨Ø¹ÙÙØ§ÙÙ Ø§ÙØ¬Ø¯ÙØ¯.`},{de:`Meine Versichertennummer lautet â¦`,ar:`Ø±ÙÙ ØªØ£ÙÙÙÙ ÙÙ ...`},{de:`Bitte bestÃ¤tigen Sie den Erhalt dieser Nachricht.`,ar:`Ø§ÙØ±Ø¬Ø§Ø¡ ØªØ£ÙÙØ¯ Ø§Ø³ØªÙØ§Ù ÙØ°Ù Ø§ÙØ±Ø³Ø§ÙØ©.`},{de:`Ist eine neue Versichertenkarte erforderlich?`,ar:`ÙÙ Ø¨Ø·Ø§ÙØ© ØªØ£ÙÙÙ Ø¬Ø¯ÙØ¯Ø© Ø¶Ø±ÙØ±ÙØ©Ø`},{de:`Mit freundlichen GrÃ¼Ãen`,ar:`ÙØ¹ Ø£Ø·ÙØ¨ Ø§ÙØªØ­ÙØ§Øª`}],sampleAnswerNotes:[`Ø¯Ø§Ø¦ÙØ§Ù Ø§Ø¨Ø¯Ø£ Ø¨Ù "Sehr geehrte Damen und Herren" ÙØ¹ Ø§ÙÙØ¤Ø³Ø³Ø§Øª.`,`Ø¶Ø¹ Ø±ÙÙ Ø§ÙØªØ£ÙÙÙ Ø¨ÙØ¶ÙØ­ ÙÙØ¬Ø¯ÙÙ Ø¨Ø³Ø±Ø¹Ø©.`,`ÙÙ ÙØ®ØªØµØ±Ø§Ù ÙÙØ­Ø¯ÙØ¯Ø§Ù.`],sampleAnswer:`Sehr geehrte Damen und Herren,

hiermit mÃ¶chte ich Ihnen mitteilen, dass ich seit dem 1. MÃ¤rz in eine neue Wohnung umgezogen bin. Bitte aktualisieren Sie meine Daten in Ihrem System.

Mein Name: Mohammed Alsalim
Versichertennummer: A123456789
Alte Adresse: HauptstraÃe 12, 60311 Frankfurt
Neue Adresse: Bergweg 8, 4. Stock, 60439 Frankfurt

Bitte bestÃ¤tigen Sie mir den Erhalt dieser E-Mail. AuÃerdem mÃ¶chte ich gerne wissen, ob ich eine neue Versichertenkarte mit der neuen Adresse beantragen muss.

Vielen Dank im Voraus.

Mit freundlichen GrÃ¼Ãen
Mohammed Alsalim`},{id:`schreiben-7-2`,taskNumber:2,typeAr:`ÙÙØªØ¯Ù: ÙÙØ§Ø´ Ø­ÙÙ ØªØ¹ÙÙÙ Ø§ÙÙØºØ© Ø§ÙØ£ÙÙØ§ÙÙØ©`,typeDe:`Forumbeitrag`,promptAr:`ÙÙ ÙÙØªØ¯Ù Ø§ÙÙÙØ§Ø¬Ø±ÙÙØ Ø´Ø®Øµ ÙÙÙÙ: "ØªØ¹ÙÙÙ Ø§ÙØ£ÙÙØ§ÙÙØ© ÙØ³ØªØ­ÙÙ Ø¨Ø¯ÙÙ ÙØ¯Ø±ÙØ³". Ø§ÙØªØ¨ Ø±Ø£ÙÙ.`,promptDe:`In einem Migranten-Forum schreibt jemand: "Ohne Lehrer kann man Deutsch nicht lernen." Schreiben Sie Ihre Meinung.`,requirements:[`Ø¹Ø¨ÙØ± Ø¹Ù Ø±Ø£ÙÙ Ø¨ÙØ¶ÙØ­`,`Ø§Ø°ÙØ± ØªØ¬Ø±Ø¨ØªÙ Ø§ÙØ´Ø®ØµÙØ©`,`Ø§Ø°ÙØ± Ø·Ø±ÙØ§Ù Ø³Ø§Ø¹Ø¯ØªÙ`,`Ø§ÙØµØ­ Ø§ÙÙØ§Ø±Ø¦ Ø¨Ø´ÙØ¡ Ø¹ÙÙÙ`],wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,usefulPhrases:[{de:`Das stimmt nur teilweise.`,ar:`ÙØ°Ø§ ØµØ­ÙØ­ Ø¬Ø²Ø¦ÙØ§Ù.`},{de:`Aus eigener Erfahrung kann ich sagen, â¦`,ar:`ÙÙ ØªØ¬Ø±Ø¨ØªÙ Ø§ÙØ´Ø®ØµÙØ©Ø Ø£Ø³ØªØ·ÙØ¹ Ø§ÙÙÙÙ Ø¥Ù...`},{de:`Ich habe vor allem mit Apps gelernt.`,ar:`ØªØ¹ÙÙÙØª Ø¨Ø´ÙÙ Ø£Ø³Ø§Ø³Ù Ø¨Ø§ÙØªØ·Ø¨ÙÙØ§Øª.`},{de:`Mein Tipp ist: â¦`,ar:`ÙØµÙØ­ØªÙ ÙÙ: ...`},{de:`Sprachpartner finden ist sehr wichtig.`,ar:`Ø¥ÙØ¬Ø§Ø¯ Ø´Ø±ÙÙ ÙÙØªØ­Ø¯Ø« ÙÙÙ Ø¬Ø¯Ø§Ù.`}],sampleAnswer:`Das stimmt meiner Meinung nach nur teilweise. NatÃ¼rlich hilft ein Lehrer enorm, vor allem bei der Aussprache und der Grammatik. Aber unmÃ¶glich ohne Lehrer? Ich denke, das ist Ã¼bertrieben.

Aus eigener Erfahrung: Ich habe das Niveau A2 hauptsÃ¤chlich mit YouTube-Videos und einer App erreicht. Erst danach habe ich einen Kurs besucht. Das Wichtigste ist, jeden Tag etwas zu Ã¼ben und mit echten Menschen zu sprechen, zum Beispiel Nachbarn oder im Sportverein.

Mein Tipp: Apps + Tandempartner + ein paar Stunden mit Lehrer = die beste Mischung.`},{id:`schreiben-7-3`,taskNumber:3,typeAr:`Ø´ÙÙÙ Ø±Ø³ÙÙØ© ÙÙ Jobcenter: ØªØ£Ø®ÙØ± ÙÙ Ø§ÙØ¯ÙØ¹`,typeDe:`Beschwerde beim Jobcenter`,promptAr:`ÙÙØ° Ø´ÙØ±ÙÙ ÙÙ ØªØ³ØªÙÙ Ø±Ø§ØªØ¨ Ø§ÙØ¨Ø·Ø§ÙØ© (BÃ¼rgergeld). Ø§ÙØªØ¨ Ø´ÙÙÙ Ø±Ø³ÙÙØ© ÙÙÙ Jobcenter.`,promptDe:`Seit zwei Monaten haben Sie kein BÃ¼rgergeld erhalten. Schreiben Sie eine Beschwerde an das Jobcenter.`,requirements:[`Ø§Ø°ÙØ± Ø§Ø³ÙÙ ÙØ±ÙÙ ÙÙÙÙ (Kundennummer)`,`Ø§Ø´Ø±Ø­ Ø§ÙÙØ´ÙÙØ© Ø¨Ø¯ÙÙØ© (ÙØªÙ Ø¢Ø®Ø± Ø¯ÙØ¹Ø©)`,`Ø§Ø·ÙØ¨ ØªÙØ¶ÙØ­Ø§Ù ÙØ­ÙØ§Ù Ø¹Ø§Ø¬ÙØ§Ù`,`Ø§Ø°ÙØ± Ø£Ù Ø§ÙÙØ¶Ø¹ Ø§ÙÙØ§ÙÙ ØµØ¹Ø¨`],wordCount:`Ø­ÙØ§ÙÙ 100 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=70`,imageAlt:`ÙÙØªØ¨ Ø±Ø³ÙÙ`,usefulPhrases:[{de:`Sehr geehrte Damen und Herren,`,ar:`Ø³ÙØ¯Ø§ØªÙ Ø³Ø§Ø¯ØªÙ Ø§ÙÙØ­ØªØ±ÙÙÙØ`},{de:`hiermit beschwere ich mich Ã¼ber â¦`,ar:`Ø¨ÙØ°Ø§ Ø£ØªÙØ¯ÙÙ Ø¨Ø´ÙÙÙ Ø¨Ø®ØµÙØµ...`},{de:`meine Kundennummer lautet â¦`,ar:`Ø±ÙÙ ÙÙÙÙ ÙÙ...`},{de:`Die letzte Zahlung erhielt ich am â¦`,ar:`Ø¢Ø®Ø± Ø¯ÙØ¹Ø© Ø§Ø³ØªÙÙØªÙØ§ ÙÙ...`},{de:`Meine finanzielle Lage ist sehr schwierig.`,ar:`ÙØ¶Ø¹Ù Ø§ÙÙØ§ÙÙ ØµØ¹Ø¨ Ø¬Ø¯Ø§Ù.`},{de:`Ich bitte um eine schnelle KlÃ¤rung.`,ar:`Ø£Ø±Ø¬Ù ØªÙØ¶ÙØ­Ø§Ù Ø¹Ø§Ø¬ÙØ§Ù.`},{de:`Mit freundlichen GrÃ¼Ãen`,ar:`ÙØ¹ Ø£Ø·ÙØ¨ Ø§ÙØªØ­ÙØ§Øª`}],sampleAnswerNotes:[`Ø§Ø³ØªØ®Ø¯Ù "hiermit beschwere ich mich" â ØµÙØºØ© Ø´ÙÙÙ Ø±Ø³ÙÙØ©.`,`Ø¶Ø¹ Ø±ÙÙ Ø§ÙÙÙÙ Ø¨ÙØ¶ÙØ­ ÙÙ Ø§ÙØ¨Ø¯Ø§ÙØ©.`,`Ø§Ø·ÙØ¨ Ø±Ø¯Ø§Ù Ø¶ÙÙ Ø¥Ø·Ø§Ø± Ø²ÙÙÙ (z.B. "innerhalb einer Woche").`],sampleAnswer:`Sehr geehrte Damen und Herren,

hiermit beschwere ich mich, dass ich seit zwei Monaten kein BÃ¼rgergeld erhalten habe. Meine Kundennummer lautet 12345678/JC.

Die letzte Zahlung erhielt ich am 15. Februar. Seitdem ist nichts mehr auf meinem Konto eingegangen, obwohl meine Bewilligung bis Ende Juli lÃ¤uft. Auf meine zwei vorherigen Anrufe habe ich leider keine Antwort bekommen.

Meine finanzielle Lage ist inzwischen sehr schwierig: Miete, Strom und Lebensmittel kann ich kaum bezahlen.

Ich bitte Sie deshalb dringend um eine schnelle KlÃ¤rung dieses Problems â am besten innerhalb einer Woche â und um eine schriftliche ErklÃ¤rung, warum die Zahlungen ausgeblieben sind.

Mit freundlichen GrÃ¼Ãen
Ahmad Khalil`}]},{id:`schreiben-8`,title:`ÙÙÙØ°Ø¬ Schreiben Ø±ÙÙ 8 â Ø±Ø³Ø§Ø¦Ù Ø¹ÙÙÙÙØ© Ø´Ø§Ø¦Ø¹Ø©`,description:`Ø«ÙØ§Ø« ÙÙØ§Ù ÙÙ Ø§ÙØ­ÙØ§Ø© Ø§ÙÙÙÙÙÙØ©: ØªØ£Ø¬ÙÙ ÙÙØ¹Ø¯Ø Ø´ÙÙÙ ÙÙ Ø·ÙØ¨ Ø£ÙÙÙØ§ÙÙØ Ø¯Ø¹ÙØ© ÙØ­ÙÙ ÙÙÙØ§Ø¯.`,tasks:[{id:`schreiben-8-1`,taskNumber:1,typeAr:`ØªØ£Ø¬ÙÙ ÙÙØ¹Ø¯ Ø·Ø¨ÙØ¨`,typeDe:`Arzttermin verschieben`,promptAr:`ÙØ§Ù Ø¹ÙØ¯Ù ÙÙØ¹Ø¯ Ø¹ÙØ¯ Ø§ÙØ·Ø¨ÙØ¨ (Hausarzt) ÙÙÙ Ø§ÙØ®ÙÙØ³ Ø§ÙØ³Ø§Ø¹Ø© 10:00 ÙÙÙ ÙØ§ ØªØ³ØªØ·ÙØ¹ Ø§ÙØ­Ø¶ÙØ± Ø¨Ø³Ø¨Ø¨ Ø§ÙØ¹ÙÙ. Ø§ÙØªØ¨ Ø±Ø³Ø§ÙØ© ÙØªØºÙÙØ± Ø§ÙÙÙØ¹Ø¯.`,promptDe:`Sie haben am Donnerstag um 10:00 einen Termin bei Ihrem Hausarzt, kÃ¶nnen aber wegen der Arbeit nicht kommen. Schreiben Sie eine E-Mail, um den Termin zu verschieben.`,requirements:[`Ø§Ø¹ØªØ°Ø± Ø¨Ø£Ø¯Ø¨`,`Ø§Ø´Ø±Ø­ Ø§ÙØ³Ø¨Ø¨ Ø¨Ø§Ø®ØªØµØ§Ø±`,`Ø§ÙØªØ±Ø­ ÙÙØ¹Ø¯ÙÙ Ø¨Ø¯ÙÙÙÙÙ`,`Ø§Ø·ÙØ¨ Ø§ÙØªØ£ÙÙØ¯ ÙØªØ§Ø¨ÙÙØ§Ù`],wordCount:`Ø­ÙØ§ÙÙ 70-80 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&w=800&q=70`,imageAlt:`ÙÙØ¹Ø¯ Ø·Ø¨Ù`,usefulPhrases:[{de:`Sehr geehrte Frau / Sehr geehrter Herr Dr. ...,`,ar:`Ø¯ÙØªÙØ±Ø©/Ø¯ÙØªÙØ± Ø§ÙÙØ­ØªØ±ÙØ`},{de:`leider kann ich meinen Termin am ... nicht wahrnehmen.`,ar:`ÙÙØ£Ø³Ù ÙØ§ Ø£Ø³ØªØ·ÙØ¹ Ø­Ø¶ÙØ± ÙÙØ¹Ø¯Ù ÙÙÙ...`},{de:`der Grund ist, dass ich beruflich verhindert bin.`,ar:`Ø§ÙØ³Ø¨Ø¨ Ø£ÙÙÙ ÙØ±ØªØ¨Ø· Ø¨Ø¹ÙÙ.`},{de:`WÃ¤re es mÃ¶glich, den Termin auf ... zu verschieben?`,ar:`ÙÙ Ø¨Ø§ÙØ¥ÙÙØ§Ù ØªØ£Ø¬ÙÙ Ø§ÙÙÙØ¹Ø¯ Ø¥ÙÙ...Ø`},{de:`Alternativ kÃ¤me auch ... in Frage.`,ar:`Ø¨Ø¯ÙØ§Ù ÙÙ Ø°ÙÙ ÙÙÙÙ Ø£ÙØ¶Ø§Ù...`},{de:`Ich bitte um eine kurze BestÃ¤tigung.`,ar:`Ø£Ø±Ø¬Ù ØªØ£ÙÙØ¯Ø§Ù ÙØµÙØ±Ø§Ù.`}],sampleAnswerNotes:[`Ø§Ø³ØªØ®Ø¯Ù ØµÙØºØ© "Sehr geehrte/r" ÙØ¹ Ø§Ø³Ù Ø§ÙØ·Ø¨ÙØ¨.`,`Ø§ÙØªØ±Ø­ ÙÙØ¹Ø¯ÙÙÙ Ø¨Ø¯ÙÙÙÙÙ Ø¹ÙÙ Ø§ÙØ£ÙÙÙ â ÙØ³Ø§Ø¹Ø¯ Ø§ÙØ³ÙØ±ØªÙØ±Ø©.`],sampleAnswer:`Sehr geehrte Frau Dr. Schmidt,

leider kann ich meinen Termin am Donnerstag um 10:00 nicht wahrnehmen. Der Grund ist, dass ich an diesem Tag beruflich verhindert bin und nicht von der Arbeit weg kann.

Ich mÃ¶chte den Termin gerne verschieben. WÃ¤re es mÃ¶glich, einen neuen Termin am kommenden Montag um 9:00 oder am Mittwoch um 16:00 zu bekommen?

Ãber eine kurze BestÃ¤tigung per E-Mail wÃ¤re ich sehr dankbar.

Vielen Dank im Voraus und mit freundlichen GrÃ¼Ãen,
Yara Hassan`},{id:`schreiben-8-2`,taskNumber:2,typeAr:`Ø´ÙÙÙ ÙÙ Ø·ÙØ¨ Ø£ÙÙÙØ§ÙÙ ÙØ¹Ø·ÙØ¨`,typeDe:`Reklamation einer Online-Bestellung`,promptAr:`Ø·ÙØ¨Øª Ø³ÙÙØ§Ø¹Ø§Øª Ø¨ÙÙØªÙØ« ÙÙ ÙØªØ¬Ø± Ø£ÙÙÙØ§ÙÙ ÙØ¨Ù Ø£Ø³Ø¨ÙØ¹. ÙØµÙØª Ø§ÙÙÙÙ ÙÙÙÙÙØ§ ÙØ§ ØªØ´ØªØºÙ Ø£ØµÙØ§Ù. Ø§ÙØªØ¨ Ø±Ø³Ø§ÙØ© Ø´ÙÙÙ ØªØ·ÙØ¨ ÙÙÙØ§ Ø¥Ø¹Ø§Ø¯Ø© Ø§ÙÙØ§Ù Ø£Ù Ø§Ø³ØªØ¨Ø¯Ø§Ù Ø§ÙÙÙØªØ¬.`,promptDe:`Sie haben vor einer Woche Bluetooth-KopfhÃ¶rer in einem Online-Shop bestellt. Heute sind sie angekommen, aber sie funktionieren nicht. Schreiben Sie eine Reklamation und fordern Sie RÃ¼ckerstattung oder Ersatz.`,requirements:[`Ø§Ø°ÙØ± Ø±ÙÙ Ø§ÙØ·ÙØ¨ ÙØªØ§Ø±ÙØ®Ù`,`ØµÙ Ø§ÙØ¹Ø·Ù Ø¨Ø¯ÙÙØ©`,`Ø§Ø·ÙØ¨ Ø­ÙÙØ§Ù ÙØ§Ø¶Ø­Ø§Ù (Ø§Ø³ØªØ±Ø¯Ø§Ø¯/Ø§Ø³ØªØ¨Ø¯Ø§Ù)`,`Ø­Ø¯ÙØ¯ Ø¥Ø·Ø§Ø±Ø§Ù Ø²ÙÙÙÙØ§Ù ÙÙØ±Ø¯Ù`],wordCount:`Ø­ÙØ§ÙÙ 90-100 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=70`,imageAlt:`Ø³ÙÙØ§Ø¹Ø§Øª Ø¨ÙÙØªÙØ«`,usefulPhrases:[{de:`mit groÃem Bedauern muss ich Ihnen mitteilen, dass ...`,ar:`ÙØ¹ Ø§ÙØ£Ø³Ù Ø§ÙØ´Ø¯ÙØ¯Ø ÙØ¬Ø¨ Ø£Ù Ø£Ø®Ø¨Ø±ÙÙ Ø£ÙÙ...`},{de:`meine Bestellnummer lautet ...`,ar:`Ø±ÙÙ Ø·ÙØ¨Ù ÙÙ...`},{de:`der Artikel funktioniert leider nicht.`,ar:`Ø§ÙÙÙØªØ¬ ÙØ§ ÙØ¹ÙÙ ÙÙØ£Ø³Ù.`},{de:`Ich bitte um RÃ¼ckerstattung des Kaufpreises.`,ar:`Ø£Ø±Ø¬Ù Ø§Ø³ØªØ±Ø¯Ø§Ø¯ Ø«ÙÙ Ø§ÙØ´Ø±Ø§Ø¡.`},{de:`Alternativ erwarte ich Ersatz innerhalb von ... Tagen.`,ar:`ÙØ¨Ø¯ÙÙØ Ø£ØªÙÙÙØ¹ ÙÙØªØ¬Ø§Ù Ø¨Ø¯ÙÙØ§Ù Ø®ÙØ§Ù...`},{de:`Bitte teilen Sie mir mit, wie wir verfahren sollen.`,ar:`Ø£Ø±Ø¬Ù Ø¥Ø®Ø¨Ø§Ø±Ù Ø¨Ø§ÙØ®Ø·ÙØ§Øª Ø§ÙØªØ§ÙÙØ©.`}],sampleAnswerNotes:[`ÙÙ ÙØ§Ø¶Ø­Ø§Ù ÙÙ ÙØµÙ Ø§ÙØ¹Ø·Ù (ÙØ§ ÙØ´Ø­Ù / ÙØ§ ÙØµØ¯Ø± ØµÙØª).`,`Ø§Ø³ØªØ®Ø¯Ù Ø±ÙÙ Ø§ÙØ·ÙØ¨ Ø¨Ø¯ÙÙØ© â ÙÙØªØ§Ø­ Ø§ÙØ±Ø¯Ù Ø§ÙØ³Ø±ÙØ¹.`],sampleAnswer:`Sehr geehrte Damen und Herren,

mit groÃem Bedauern muss ich mich Ã¼ber Ihre Lieferung beschweren. Meine Bestellnummer lautet B-2025-09812 und wurde am 15. MÃ¤rz aufgegeben.

Heute sind die Bluetooth-KopfhÃ¶rer angekommen, jedoch lassen sie sich Ã¼berhaupt nicht einschalten. Ich habe sie mehrere Stunden geladen, aber das GerÃ¤t reagiert nicht. Offensichtlich liegt ein Defekt vor.

Ich bitte Sie hÃ¶flich um eine RÃ¼ckerstattung des vollen Kaufpreises (89,99 â¬) auf mein ursprÃ¼ngliches Konto. Alternativ akzeptiere ich auch einen kostenlosen Ersatz innerhalb von 7 Tagen.

Bitte teilen Sie mir bis Ende der Woche mit, wie wir verfahren sollen, damit ich die defekte Ware zurÃ¼cksenden kann.

Mit freundlichen GrÃ¼Ãen,
Omar Aziz`},{id:`schreiben-8-3`,taskNumber:3,typeAr:`Ø¯Ø¹ÙØ© ØµØ¯ÙÙ ÙØ­ÙÙ ÙÙÙØ§Ø¯`,typeDe:`Einladung zum Geburtstag`,promptAr:`Ø³ÙÙÙÙ Ø¹ÙØ¯ ÙÙÙØ§Ø¯Ù Ø§ÙØ³Ø¨Øª Ø§ÙÙØ§Ø¯Ù ÙÙ Ø§ÙØ¨ÙØª. Ø§ÙØªØ¨ Ø±Ø³Ø§ÙØ© ÙØµØ¯ÙÙÙ ØªØ¯Ø¹ÙÙ ÙÙØ­ÙÙ.`,promptDe:`Am kommenden Samstag haben Sie Geburtstag und feiern zu Hause. Schreiben Sie Ihrem Freund eine E-Mail und laden Sie ihn ein.`,requirements:[`Ø§Ø¨Ø¯Ø£ Ø¨ØµÙØºØ© Ø´Ø®ØµÙÙØ© ÙØ£Ø®Ø¨Ø±Ù Ø¨Ø§ÙÙÙØ§Ø³Ø¨Ø©`,`Ø­Ø¯ÙØ¯ ÙÙØ§Ù ÙØ²ÙØ§Ù ÙÙÙØ¶ÙØ¹ Ø§ÙØ­ÙÙ`,`Ø§Ø·ÙØ¨ ÙÙÙ Ø£Ù ÙØ­Ø¶Ø± Ø´ÙØ¦Ø§Ù (ÙØ´Ø±ÙØ¨/Ø³ÙØ·Ø©)`,`Ø§Ø·ÙØ¨ Ø§ÙØªØ£ÙÙØ¯ ÙØ¨Ù Ø§ÙØ¬ÙØ¹Ø©`],wordCount:`Ø­ÙØ§ÙÙ 70-80 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=70`,imageAlt:`Ø­ÙÙ Ø¹ÙØ¯ ÙÙÙØ§Ø¯`,usefulPhrases:[{de:`Hallo Karim,`,ar:`ÙØ±Ø­Ø¨Ø§Ù ÙØ±ÙÙØ`},{de:`wie geht es dir? Mir geht es super!`,ar:`ÙÙÙ Ø­Ø§ÙÙØ Ø£ÙØ§ Ø¨Ø®ÙØ± Ø¬Ø¯Ø§Ù!`},{de:`am Samstag ist mein Geburtstag und ich feiere zu Hause.`,ar:`Ø§ÙØ³Ø¨Øª Ø¹ÙØ¯ ÙÙÙØ§Ø¯Ù ÙØ£Ø­ØªÙÙ ÙÙ Ø§ÙØ¨ÙØª.`},{de:`Es geht um 19:00 Uhr los.`,ar:`ÙØ¨Ø¯Ø£ Ø§ÙØ­ÙÙ Ø§ÙØ³Ø§Ø¹Ø© 19.`},{de:`Bring bitte ... mit, wenn du magst.`,ar:`Ø£Ø­Ø¶Ø± ÙØ¹Ù... ÙÙ ÙØ¶ÙÙ.`},{de:`Bitte sag mir Bescheid, ob du kommst.`,ar:`Ø£Ø®Ø¨Ø±ÙÙ Ø¥Ø°Ø§ ÙÙØª Ø³ØªØ£ØªÙ.`},{de:`Ich freue mich riesig auf dich!`,ar:`Ø£ØªØ·ÙÙØ¹ ÙØ±Ø¤ÙØªÙ Ø¨Ø´Ø¯ÙØ©!`}],sampleAnswerNotes:[`Ø§Ø³ØªØ®Ø¯Ù ÙÙØ¬Ø© ÙØ¯ÙØ¯Ø© "du" â Ø¯Ø¹ÙØ© Ø¨ÙÙ Ø£ØµØ¯ÙØ§Ø¡.`,`Ø­Ø¯ÙØ¯ Ø§ÙØªØ§Ø±ÙØ® ÙØ§ÙÙÙØª Ø¨ÙØ¶ÙØ­.`],sampleAnswer:`Hallo Karim,

wie geht's dir? Mir geht es super, denn ich habe groÃartige Neuigkeiten: Am Samstag, dem 22. MÃ¤rz, habe ich endlich Geburtstag! Ich feiere bei mir zu Hause (HauptstraÃe 17, 3. Stock).

Es geht um 19:00 Uhr los, und es gibt Pizza, Musik und natÃ¼rlich Kuchen. Wenn du magst, bring bitte einen Salat oder ein paar GetrÃ¤nke mit â wir teilen das wie immer.

Bitte sag mir bis Freitag Bescheid, ob du dabei bist. Ich freue mich riesig, dich zu sehen!

Liebe GrÃ¼Ãe,
Lina`}]},{id:`schreiben-9`,title:`ÙÙÙØ°Ø¬ Schreiben Ø±ÙÙ 9 â ÙÙØ§ÙÙ Ø¹ÙÙ ÙØ³ÙÙ`,description:`Ø«ÙØ§Ø« ÙÙØ§Ù: ØªÙØ¯ÙÙ ÙØªØ¯Ø±ÙØ¨Ø Ø´ÙÙÙ ÙÙÙØ¤Ø¬ÙØ± Ø¹Ù Ø§ÙØ¹ÙÙØ Ø·ÙØ¨ ÙÙÙ Ø¥Ø¬Ø§Ø²Ø©.`,tasks:[{id:`schreiben-9-1`,taskNumber:1,typeAr:`Ø·ÙØ¨ ØªØ¯Ø±ÙØ¨ (Praktikum) ÙÙ Ø´Ø±ÙØ©`,typeDe:`Bewerbung um ein Praktikum`,promptAr:`Ø±Ø£ÙØª Ø¥Ø¹ÙØ§ÙØ§Ù Ø¹Ù ØªØ¯Ø±ÙØ¨ ØµÙÙÙ ÙØ¯ÙØªÙ 6 Ø£Ø³Ø§Ø¨ÙØ¹ ÙÙ Ø´Ø±ÙØ© ÙÙØ¯Ø³Ø©. Ø§ÙØªØ¨ Ø±Ø³Ø§ÙØ© ØªÙØ¯ÙÙ ÙØµÙØ±Ø©.`,promptDe:`Sie haben eine Anzeige fÃ¼r ein 6-wÃ¶chiges Sommerpraktikum in einer Ingenieursfirma gesehen. Schreiben Sie eine kurze Bewerbung.`,requirements:[`Ø§Ø°ÙØ± ÙØµØ¯Ø± Ø¥Ø¹ÙØ§Ù Ø§ÙØªØ¯Ø±ÙØ¨`,`Ø§Ø´Ø±Ø­ ÙÙ ØªÙÙÙ ÙÙÙØ§Ø°Ø§ Ø£ÙØª ÙÙØªÙÙ`,`Ø§Ø°ÙØ± ÙÙØ§Ø±Ø© Ø£Ù Ø®Ø¨Ø±Ø© Ø³Ø§Ø¨ÙØ© (ÙØ§Ø­Ø¯Ø©)`,`Ø§Ø·ÙØ¨ ÙÙØ¹Ø¯ ÙÙØ§Ø¨ÙØ©`],wordCount:`Ø­ÙØ§ÙÙ 90-100 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=70`,imageAlt:`ØªÙØ¯ÙÙ ÙØ¸ÙÙØ©`,usefulPhrases:[{de:`mit groÃem Interesse habe ich Ihre Anzeige auf ... gelesen.`,ar:`ÙØ±Ø£Øª Ø¥Ø¹ÙØ§ÙÙÙ Ø¨Ø§ÙØªÙØ§Ù ÙØ¨ÙØ± Ø¹ÙÙ...`},{de:`hiermit bewerbe ich mich um ein Praktikum als ...`,ar:`Ø¨ÙØ°Ø§ Ø£ØªÙØ¯ÙÙ ÙØªØ¯Ø±ÙØ¨ ÙÙ...`},{de:`Ich studiere derzeit ... im ... Semester.`,ar:`Ø£Ø¯Ø±Ø³ Ø­Ø§ÙÙØ§Ù... ÙÙ Ø§ÙÙØµÙ...`},{de:`Besonders interessiert mich Ihr Bereich ...`,ar:`ÙÙÙÙÙÙ Ø®ØµÙØµØ§Ù ÙØ¬Ø§ÙÙÙ...`},{de:`Erste Erfahrungen habe ich bereits bei ... gesammelt.`,ar:`Ø§ÙØªØ³Ø¨Øª Ø®Ø¨Ø±Ø© Ø£ÙÙÙÙÙØ© ÙÙ...`},{de:`Ãber die MÃ¶glichkeit zu einem VorstellungsgesprÃ¤ch wÃ¼rde ich mich sehr freuen.`,ar:`Ø³Ø£ÙÙÙ ÙÙØªÙÙØ§Ù ÙÙØ±ØµØ© Ø§ÙÙÙØ§Ø¨ÙØ©.`}],sampleAnswer:`Sehr geehrte Damen und Herren,

mit groÃem Interesse habe ich Ihre Anzeige auf der Website "Praktikum.info" gelesen. Hiermit bewerbe ich mich um das ausgeschriebene 6-wÃ¶chige Praktikum als Ingenieurassistent.

Ich studiere derzeit Maschinenbau im 4. Semester an der TU Berlin und suche eine praktische Erfahrung im Sommer 2025. Besonders interessiert mich Ihr Bereich der erneuerbaren Energien, da ich meine Bachelorarbeit dazu plane.

Erste Erfahrungen habe ich bereits in einem 3-monatigen Werkstudentenjob bei einer kleineren Firma gesammelt, wo ich technische Zeichnungen mit AutoCAD erstellt habe.

Ãber die MÃ¶glichkeit zu einem VorstellungsgesprÃ¤ch wÃ¼rde ich mich sehr freuen.

Mit freundlichen GrÃ¼Ãen,
Tarek Ibrahim`},{id:`schreiben-9-2`,taskNumber:2,typeAr:`Ø´ÙÙÙ ÙÙÙØ¤Ø¬ÙØ± Ø¹Ù Ø¹ÙÙ (Schimmel) ÙÙ Ø§ÙØ­ÙÙØ§Ù`,typeDe:`Beschwerde beim Vermieter wegen Schimmel`,promptAr:`ÙÙØ° Ø´ÙØ± Ø¸ÙØ± Ø¹ÙÙ (Schimmel) ÙØ¨ÙØ± Ø¹ÙÙ Ø¬Ø¯Ø§Ø± Ø­ÙÙØ§ÙÙ. Ø­Ø§ÙÙØª Ø§ÙØ§ØªÙØµØ§Ù Ø¨Ø§ÙÙØ¤Ø¬ÙØ± ÙØ±ÙØªÙÙ Ø¨Ø¯ÙÙ Ø±Ø¯Ù. Ø§ÙØªØ¨ Ø±Ø³Ø§ÙØ© Ø±Ø³ÙÙÙØ©.`,promptDe:`Seit einem Monat zeigt sich an Ihrer Badezimmerwand groÃer Schimmel. Sie haben Ihren Vermieter zweimal angerufen, aber keine Antwort bekommen. Schreiben Sie einen formellen Brief.`,requirements:[`Ø§Ø°ÙØ± Ø¹ÙÙØ§Ù Ø§ÙØ´ÙÙØ© ÙØªØ§Ø±ÙØ® Ø¸ÙÙØ± Ø§ÙÙØ´ÙÙØ©`,`ØµÙ Ø§ÙØ¹ÙÙ Ø¨Ø¯ÙÙØ© (ÙÙØ§ÙÙ/Ø­Ø¬ÙÙ)`,`Ø§Ø°ÙØ± Ø§ÙÙØ­Ø§ÙÙØ§Øª Ø§ÙØ³Ø§Ø¨ÙØ© ÙÙØªÙØ§ØµÙ`,`Ø§Ø·ÙØ¨ ØªØµÙÙØ­Ø§Ù Ø¹Ø§Ø¬ÙØ§Ù ÙØªÙÙÙØ­Ø§Ù ÙØªØ®ÙÙØ¶ Ø§ÙØ¥ÙØ¬Ø§Ø± (Mietminderung)`],wordCount:`Ø­ÙØ§ÙÙ 100-120 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1564540586988-aa4e53c3d799?auto=format&fit=crop&w=800&q=70`,imageAlt:`Ø­ÙÙØ§Ù`,usefulPhrases:[{de:`hiermit teile ich Ihnen mit, dass ...`,ar:`Ø¨ÙØ°Ø§ Ø£Ø¨ÙØºÙÙ Ø£ÙÙ...`},{de:`in der Wohnung ... ist ein erheblicher Mangel aufgetreten.`,ar:`ÙÙ Ø§ÙØ´ÙÙØ©... Ø¸ÙØ± Ø¹ÙØ¨ ÙØ¨ÙØ±.`},{de:`an der Wand des Badezimmers hat sich ein groÃer Schimmelfleck gebildet.`,ar:`Ø¹ÙÙ Ø¬Ø¯Ø§Ø± Ø§ÙØ­ÙÙØ§Ù ØªÙÙÙÙØª Ø¨ÙØ¹Ø© Ø¹ÙÙ ÙØ¨ÙØ±Ø©.`},{de:`der Schimmel breitet sich tÃ¤glich weiter aus.`,ar:`Ø§ÙØ¹ÙÙ ÙØªÙØ¯ÙØ¯ ÙÙÙÙÙØ§Ù.`},{de:`Ich habe Sie bereits zweimal telefonisch zu erreichen versucht.`,ar:`Ø­Ø§ÙÙØª Ø§ÙØ§ØªÙØµØ§Ù ÙØ§ØªÙÙÙØ§Ù ÙØ±ÙØªÙÙ Ø¨Ø¯ÙÙ ÙØªÙØ¬Ø©.`},{de:`Ich fordere Sie auf, den Schaden innerhalb von ... Tagen zu beheben.`,ar:`Ø£Ø·Ø§ÙØ¨ÙÙ Ø¨Ø¥ØµÙØ§Ø­ Ø§ÙØ¶Ø±Ø± Ø®ÙØ§Ù... ÙÙÙØ§Ù.`},{de:`Andernfalls behalte ich mir eine Mietminderung vor.`,ar:`ÙØ¥ÙÙØ§ ÙØ³Ø£Ø­ØªÙØ¸ Ø¨Ø­ÙÙ ØªØ®ÙÙØ¶ Ø§ÙØ¥ÙØ¬Ø§Ø±.`}],sampleAnswer:`Sehr geehrter Herr MÃ¼ller,

hiermit teile ich Ihnen mit, dass in der von mir gemieteten Wohnung in der GoethestraÃe 24, 1. Stock, ein erheblicher Mangel aufgetreten ist.

Seit etwa einem Monat hat sich an der Wand des Badezimmers (neben der Dusche) ein groÃer Schimmelfleck gebildet, der mittlerweile etwa 50Ã60 cm groÃ ist und sich tÃ¤glich weiter ausbreitet. Der Geruch ist sehr unangenehm und ich befÃ¼rchte gesundheitliche Folgen fÃ¼r meine Familie, besonders fÃ¼r meinen 4-jÃ¤hrigen Sohn.

Ich habe Sie bereits am 5. und 12. MÃ¤rz telefonisch zu erreichen versucht, leider ohne Erfolg.

Ich fordere Sie hiermit schriftlich auf, den Schaden innerhalb von 14 Tagen fachgerecht zu beheben. Andernfalls werde ich eine angemessene Mietminderung von 20% vornehmen, wie es das Mietrecht vorsieht.

Mit freundlichen GrÃ¼Ãen,
Familie Khaled`},{id:`schreiben-9-3`,taskNumber:3,typeAr:`Ø·ÙØ¨ ÙÙÙ Ø¥Ø¬Ø§Ø²Ø© ÙÙ Ø§ÙÙØ¯ÙØ±`,typeDe:`Urlaubsantrag beim Chef`,promptAr:`ØªØ­ØªØ§Ø¬ ÙÙÙØ§Ù Ø¥Ø¬Ø§Ø²Ø© ÙØ­Ø¶ÙØ± Ø¬ÙØ³Ø© ÙÙÙÙØ© ÙÙ BÃ¼rgeramt. Ø§ÙØªØ¨ Ø±Ø³Ø§ÙØ© ÙØµÙØ±Ø© ÙÙØ¯ÙØ±Ù.`,promptDe:`Sie brauchen einen Urlaubstag fÃ¼r einen wichtigen Termin beim BÃ¼rgeramt. Schreiben Sie eine kurze E-Mail an Ihren Chef.`,requirements:[`Ø§Ø´Ø±Ø­ Ø§ÙØ­Ø§Ø¬Ø© Ø¨Ø¥ÙØ¬Ø§Ø²`,`Ø­Ø¯ÙØ¯ Ø§ÙØªØ§Ø±ÙØ® Ø§ÙÙØ·ÙÙØ¨`,`Ø§ÙØªØ±Ø­ ØªØ£Ø¬ÙÙ/ØªØºØ·ÙØ© Ø§ÙÙÙØ§ÙÙ`,`Ø§Ø·ÙØ¨ Ø§ÙÙÙØ§ÙÙØ©`],wordCount:`Ø­ÙØ§ÙÙ 60-70 ÙÙÙØ©`,imageUrl:`https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=800&q=70`,imageAlt:`ÙÙØªØ¨`,usefulPhrases:[{de:`Sehr geehrter Herr ... / Sehr geehrte Frau ...,`,ar:`Ø³ÙØ¯Ù/Ø³ÙØ¯ØªÙ Ø§ÙÙØ­ØªØ±Ù/Ø©Ø`},{de:`hiermit beantrage ich fÃ¼r den ... einen Tag Urlaub.`,ar:`Ø¨ÙØ°Ø§ Ø£Ø·ÙØ¨ ÙÙÙ Ø¥Ø¬Ø§Ø²Ø© Ø¨ØªØ§Ø±ÙØ®...`},{de:`der Grund ist ein verbindlicher Termin bei ...`,ar:`Ø§ÙØ³Ø¨Ø¨ ÙÙØ¹Ø¯ Ø¥ÙØ²Ø§ÙÙ ÙØ¯Ù...`},{de:`Meine Aufgaben werde ich vorher abschlieÃen.`,ar:`Ø³Ø£ÙÙÙ ÙÙØ§ÙÙÙ ÙØ¨Ù Ø°ÙÙ.`},{de:`Frau / Herr ... vertritt mich an diesem Tag.`,ar:`Ø§ÙØ³ÙØ¯/Ø©... Ø³ØªØºØ·ÙÙ ÙÙØ§ÙÙ.`},{de:`Ãber Ihre Genehmigung wÃ¤re ich sehr dankbar.`,ar:`Ø³Ø£ÙÙÙ ÙÙØªÙÙØ§Ù ÙÙÙØ§ÙÙØªÙÙ.`}],sampleAnswer:`Sehr geehrter Herr Becker,

hiermit beantrage ich fÃ¼r den 28. MÃ¤rz einen Tag Urlaub. Der Grund ist ein verbindlicher Termin beim BÃ¼rgeramt zur VerlÃ¤ngerung meines Aufenthaltstitels, der nicht verschoben werden kann.

Meine laufenden Aufgaben werde ich vorher vollstÃ¤ndig abschlieÃen, und Frau Hoffmann hat zugesagt, dringende E-Mails an diesem Tag zu beantworten.

Ãber Ihre Genehmigung wÃ¤re ich sehr dankbar.

Mit freundlichen GrÃ¼Ãen,
Sara Halabi`}]},{id:`schreiben-10`,title:`Schreiben 10 â Ø§ÙØªÙØ§ØµÙ Ø§ÙØ±ÙÙÙ`,description:`Ø«ÙØ§Ø« ÙÙØ§ÙÙ ÙØªØ§Ø¨ÙÙØ© Ø¹Ù Ø§ÙØ¨Ø±ÙØ¯ Ø§ÙØ¥ÙÙØªØ±ÙÙÙ ÙØ§ÙØªØ·Ø¨ÙÙØ§Øª Ø§ÙØ±ÙÙÙÙØ©.`,tasks:[{id:`schreiben-10-1`,taskNumber:1,typeAr:`Ø¨Ø±ÙØ¯ ÙØµØ¯ÙÙ Ø¹Ù ÙØ´ÙÙØ© ØªÙÙÙÙØ©`,typeDe:`E-Mail an einen Freund Ã¼ber ein Technik-Problem`,promptAr:`Ø¥Ø®ÙØªÙ ÙØ·ÙØ¨ÙÙ ÙÙÙ ÙØ³Ø§Ø¹Ø¯Ø©. Ø­Ø§Ø³ÙØ¨Ù ÙØ§ ÙØ¹ÙÙ ÙÙØ§ ØªØ³ØªØ·ÙØ¹ ØªØ³ÙÙÙ ÙØ§Ø¬Ø¨ Ø§ÙØ¬Ø§ÙØ¹Ø©. Ø§ÙØªØ¨ ÙØµØ¯ÙÙÙ ÙÙØ³Ù.`,promptDe:`Ihre Geschwister bitten Sie um Hilfe. Ihr Computer funktioniert nicht und Sie kÃ¶nnen die Uni-Hausaufgabe nicht abgeben. Schreiben Sie an Ihren Freund Yusuf.`,requirements:[`Ø§Ø´Ø±Ø­ Ø§ÙÙØ´ÙÙØ©`,`Ø§Ø³Ø£Ù Ø¹Ù ÙØ³Ø§Ø¹Ø¯Ø© (ÙÙ ÙÙÙÙÙ Ø§Ø³ØªØ®Ø¯Ø§Ù Ø­Ø§Ø³ÙØ¨ÙØ)`,`Ø­Ø¯ÙØ¯ ÙØªÙ ØªØ±ÙØ¯ Ø§ÙÙØ¬ÙØ¡`,`Ø§Ø·ÙØ¨ Ø§ÙØ±Ø¯Ù Ø§ÙØ³Ø±ÙØ¹`],wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,usefulPhrases:[{de:`Hallo Yusuf, wie geht es dir?`,ar:`ÙØ±Ø­Ø¨Ø§ ÙÙØ³ÙØ ÙÙÙ Ø­Ø§ÙÙØ`},{de:`Ich habe ein groÃes Problem.`,ar:`Ø¹ÙØ¯Ù ÙØ´ÙÙØ© ÙØ¨ÙØ±Ø©.`},{de:`Mein Computer ist kaputt.`,ar:`Ø­Ø§Ø³ÙØ¨Ù ÙØ¹Ø·ÙÙ.`},{de:`Darf ich heute zu dir kommen und deinen Laptop benutzen?`,ar:`ÙÙ Ø£Ø³ØªØ·ÙØ¹ Ø£Ù Ø¢ØªÙ Ø§ÙÙÙÙ ÙØ£Ø³ØªØ®Ø¯Ù Ø­Ø§Ø³ÙØ¨ÙØ`},{de:`Ich muss die Hausaufgabe bis morgen abgeben.`,ar:`ÙØ¬Ø¨ Ø£Ù Ø£Ø³ÙÙÙ Ø§ÙÙØ§Ø¬Ø¨ ØºØ¯Ø§Ù.`},{de:`Bitte antworte schnell!`,ar:`Ø£Ø±Ø¬Ù Ø§ÙØ±Ø¯Ù Ø³Ø±ÙØ¹Ø§Ù!`}],sampleAnswer:`Hallo Yusuf,

ich hoffe, dir geht es gut. Ich habe ein groÃes Problem: Mein Computer funktioniert seit heute Morgen nicht mehr â der Bildschirm bleibt schwarz, auch nach einem Neustart.

Das ist ein Notfall, weil ich bis morgen 18 Uhr meine Hausaufgabe in Informatik abgeben muss. Darf ich heute Abend ab 19 Uhr zu dir kommen und deinen Laptop benutzen? Ich brauche nur 2-3 Stunden, dann bin ich fertig.

Bitte antworte mir schnell, am besten per WhatsApp.

Vielen Dank im Voraus!
Liebe GrÃ¼Ãe,
Karim`},{id:`schreiben-10-2`,taskNumber:2,typeAr:`ØªÙÙÙÙ ÙÙØªØ¬ Ø§Ø´ØªØ±ÙØªÙ Ø¥ÙÙØªØ±ÙÙÙÙØ§Ù`,typeDe:`Bewertung eines online gekauften Produkts`,promptAr:`Ø§Ø´ØªØ±ÙØª Ø³ÙÙØ§Ø¹Ø© Ø¨ÙÙØªÙØ« ÙÙ Amazon ÙÙÙÙ Ø§ÙØ¬ÙØ¯Ø© Ø³ÙÙØ¦Ø©. Ø§ÙØªØ¨ ØªÙÙÙÙØ§Ù ÙÙØ¶ÙØ¹ÙÙØ§Ù.`,promptDe:`Sie haben einen Bluetooth-KopfhÃ¶rer bei Amazon gekauft, aber die QualitÃ¤t ist schlecht. Schreiben Sie eine sachliche Bewertung.`,requirements:[`Ø§Ø°ÙØ± Ø§Ø³Ù Ø§ÙÙÙØªØ¬ ÙØªØ§Ø±ÙØ® Ø§ÙØ´Ø±Ø§Ø¡`,`Ø§Ø´Ø±Ø­ Ø«ÙØ§Ø« ÙØ´Ø§ÙÙ ÙØ§Ø¬ÙØªÙØ§`,`Ø§Ø°ÙØ± Ø´ÙØ¦Ø§Ù Ø¥ÙØ¬Ø§Ø¨ÙØ§Ù (Ø¥Ù ÙØ¬Ø¯)`,`ÙØµÙ Ø£Ù ÙØ§ ØªÙØµÙ Ø¨Ø§ÙÙÙØªØ¬ ÙÙØ¢Ø®Ø±ÙÙ`],wordCount:`Ø­ÙØ§ÙÙ 100-120 ÙÙÙØ©`,usefulPhrases:[{de:`Ich habe den KopfhÃ¶rer am ... gekauft.`,ar:`Ø§Ø´ØªØ±ÙØª Ø§ÙØ³ÙÙØ§Ø¹Ø© ÙÙ...`},{de:`Leider bin ich enttÃ¤uscht.`,ar:`ÙÙØ£Ø³Ù Ø£ÙØ§ ÙØ®ÙÙØ¨ Ø§ÙØ£ÙÙ.`},{de:`Der Akku hÃ¤lt nur ...`,ar:`Ø§ÙØ¨Ø·ÙØ§Ø±ÙÙØ© ØªØ¯ÙÙ ÙÙØ·...`},{de:`Die SoundqualitÃ¤t ist mittelmÃ¤Ãig.`,ar:`Ø¬ÙØ¯Ø© Ø§ÙØµÙØª ÙØªÙØ³ÙØ·Ø©.`},{de:`Was mir gut gefÃ¤llt, ist ...`,ar:`ÙØ§ ÙØ¹Ø¬Ø¨ÙÙ ÙÙ...`},{de:`Ich kann das Produkt nicht weiterempfehlen.`,ar:`ÙØ§ Ø£ÙØµØ­ Ø¨ÙØ°Ø§ Ø§ÙÙÙØªØ¬.`}],sampleAnswer:`Bewertung: Bluetooth-KopfhÃ¶rer "SoundPro X3"
Gekauft am 15. Februar 2026.

Leider bin ich von dem Produkt enttÃ¤uscht. Erstens hÃ¤lt der Akku nur 3 Stunden statt der versprochenen 12 Stunden. Zweitens reiÃt die Bluetooth-Verbindung alle paar Minuten ab, besonders wenn das Handy in der Tasche ist. Drittens ist die LautstÃ¤rke zu leise â in der U-Bahn hÃ¶re ich fast nichts.

Was mir gut gefÃ¤llt: Das Design ist modern und der Tragekomfort ist gut. Die KopfhÃ¶rer drÃ¼cken nicht auf den Ohren.

Insgesamt kann ich das Produkt nicht empfehlen. FÃ¼r 49 â¬ hatte ich mehr erwartet. Wer bessere KlangqualitÃ¤t sucht, sollte mehr investieren oder eine andere Marke wÃ¤hlen.

Bewertung: 2 von 5 Sternen.`},{id:`schreiben-10-3`,taskNumber:3,typeAr:`Ø·ÙØ¨ Ø§ÙØºØ§Ø¡ Ø§Ø´ØªØ±Ø§Ù Ø¥ÙÙØªØ±ÙÙÙ`,typeDe:`Schriftliche KÃ¼ndigung eines Online-Abos`,promptAr:`ØªØ±ÙØ¯ Ø¥ÙØºØ§Ø¡ Ø§Ø´ØªØ±Ø§Ù Netflix Ø§ÙØ°Ù ØªØ¯ÙØ¹ ÙÙÙ 17,99 â¬ Ø´ÙØ±ÙÙØ§Ù. Ø§ÙØªØ¨ ÙØ®Ø¯ÙØ© Ø§ÙØ¹ÙÙØ§Ø¡.`,promptDe:`Sie mÃ¶chten Ihr Netflix-Abo fÃ¼r 17,99 â¬ im Monat kÃ¼ndigen. Schreiben Sie an den Kundenservice.`,requirements:[`Ø§Ø°ÙØ± Ø¨ÙØ§ÙØ§ØªÙ ÙØ±ÙÙ Ø§ÙØ§Ø´ØªØ±Ø§Ù`,`Ø§Ø·ÙØ¨ Ø§ÙØ¥ÙØºØ§Ø¡ ØµØ±Ø§Ø­Ø©Ù`,`Ø­Ø¯ÙØ¯ Ø§ÙØªØ§Ø±ÙØ® Ø§ÙÙØ·ÙÙØ¨ ÙÙØ¥ÙÙØ§Ø¡`,`Ø§Ø·ÙØ¨ ØªØ£ÙÙØ¯Ø§Ù ÙØªØ§Ø¨ÙÙØ§Ù`],wordCount:`Ø­ÙØ§ÙÙ 70 ÙÙÙØ©`,usefulPhrases:[{de:`Sehr geehrte Damen und Herren,`,ar:`Ø³ÙÙØ¯Ø§ØªÙ Ø³Ø§Ø¯ØªÙØ`},{de:`hiermit kÃ¼ndige ich mein Abonnement zum nÃ¤chstmÃ¶glichen Termin.`,ar:`Ø¨ÙØ°Ø§ Ø£ÙØºÙ Ø§Ø´ØªØ±Ø§ÙÙ Ø¨Ø£ÙØ±Ø¨ ÙØ±ØµØ©.`},{de:`Meine Kunden-Nummer lautet: ...`,ar:`Ø±ÙÙ Ø²Ø¨ÙÙÙ ÙÙ...`},{de:`Ich bitte um schriftliche BestÃ¤tigung.`,ar:`Ø£Ø±Ø¬Ù Ø§ÙØªØ£ÙÙØ¯ ÙØªØ§Ø¨ÙÙØ§Ù.`},{de:`Bitte stornieren Sie auch zukÃ¼nftige Abbuchungen.`,ar:`Ø£Ø±Ø¬Ù Ø¥ÙÙØ§Ù Ø§ÙØ®ØµÙÙØ§Øª Ø§ÙÙØ³ØªÙØ¨ÙÙÙØ©.`}],sampleAnswer:`Sehr geehrte Damen und Herren,

hiermit kÃ¼ndige ich mein Netflix-Abonnement zum nÃ¤chstmÃ¶glichen Termin. Meine Kundennummer lautet 4587-2298-XY und das Abo wird unter der E-Mail kasem@gmail.com gefÃ¼hrt.

Ich bitte um eine schriftliche BestÃ¤tigung mit dem genauen Beendigungsdatum sowie um die Einstellung zukÃ¼nftiger Abbuchungen von meinem Konto.

Mit freundlichen GrÃ¼Ãen,
Mahmoud Kasem`}]},{id:`schreiben-11`,title:`Schreiben 11 â Ø§ÙÙÙØ§ÙÙ Ø§ÙØ±Ø³ÙÙÙØ©`,description:`ÙÙØ§ÙÙ ÙØªØ§Ø¨Ø© Ø±Ø³ÙÙÙØ©: Ø´ÙÙÙ ÙØ´Ø±ÙØ©Ø Ø·ÙØ¨ ÙÙØ¹Ø¯Ø Ø±ÙØ¶ Ø¯Ø¹ÙØ© Ø¨Ø£Ø¯Ø¨.`,tasks:[{id:`schreiben-11-1`,taskNumber:1,typeAr:`Ø´ÙÙÙ ÙØ´Ø±ÙØ© Ø§ÙÙÙØ±Ø¨Ø§Ø¡`,typeDe:`Beschwerde beim Stromanbieter`,promptAr:`ÙØ§ØªÙØ±Ø© Ø§ÙÙÙØ±Ø¨Ø§Ø¡ Ø¹Ø§ÙÙÙØ© Ø¬Ø¯ÙØ§Ù ÙØ°Ø§ Ø§ÙØ´ÙØ± (350 â¬ Ø¨Ø¯Ù 90 â¬). Ø§ÙØªØ¨ Ø´ÙÙÙ Ø±Ø³ÙÙÙØ©.`,promptDe:`Ihre Stromrechnung ist in diesem Monat sehr hoch (350 â¬ statt 90 â¬). Schreiben Sie eine formelle Beschwerde.`,requirements:[`Ø§Ø°ÙØ± Ø±ÙÙ Ø§ÙØ²Ø¨ÙÙ ÙØ§ÙØ¹Ø¯Ø§Ø¯`,`Ø§Ø´Ø±Ø­ Ø§ÙÙØ´ÙÙØ© Ø¨Ø¯ÙÙØ©`,`Ø§Ø·ÙØ¨ ÙØ­Øµ Ø§ÙØ¹Ø¯Ø§Ø¯`,`Ø­Ø¯ÙØ¯ ÙÙÙØ© ÙÙØ±Ø¯Ù`],wordCount:`Ø­ÙØ§ÙÙ 100-120 ÙÙÙØ©`,usefulPhrases:[{de:`Sehr geehrte Damen und Herren,`,ar:`Ø³ÙÙØ¯Ø§ØªÙ Ø³Ø§Ø¯ØªÙØ`},{de:`mit groÃem Erstaunen habe ich Ihre Rechnung erhalten.`,ar:`Ø¨Ø§Ø³ØªØºØ±Ø§Ø¨ ÙØ¨ÙØ± ØªÙÙÙÙØª ÙØ§ØªÙØ±ØªÙÙ.`},{de:`Meine Kundennummer ist ..., der ZÃ¤hlerstand ...`,ar:`Ø±ÙÙ Ø²Ø¨ÙÙÙ... ÙØ±ÙÙ Ø§ÙØ¹Ø¯ÙØ§Ø¯...`},{de:`Ich kann mir den hohen Betrag nicht erklÃ¤ren.`,ar:`ÙØ§ Ø£Ø³ØªØ·ÙØ¹ ØªÙØ³ÙØ± Ø§ÙÙØ¨ÙØº Ø§ÙÙØ¨ÙØ±.`},{de:`Bitte Ã¼berprÃ¼fen Sie den ZÃ¤hler.`,ar:`Ø£Ø±Ø¬Ù ÙØ­Øµ Ø§ÙØ¹Ø¯ÙØ§Ø¯.`},{de:`Bis zur KlÃ¤rung bitte ich, die Abbuchung auszusetzen.`,ar:`Ø­ØªÙÙ Ø§ÙØªÙØ¶ÙØ­ Ø£Ø±Ø¬Ù ÙÙÙ Ø§ÙØ®ØµÙ.`},{de:`Ich erwarte Ihre Antwort innerhalb von 14 Tagen.`,ar:`Ø£ÙØªØ¸Ø± Ø±Ø¯ÙÙÙ Ø®ÙØ§Ù 14 ÙÙÙØ§Ù.`}],sampleAnswer:`Sehr geehrte Damen und Herren,

mit groÃem Erstaunen habe ich Ihre Stromrechnung vom 28. Februar 2026 erhalten. Der Betrag belÃ¤uft sich auf 350 â¬, obwohl meine durchschnittliche Monatsrechnung in den letzten zwÃ¶lf Monaten zwischen 80 â¬ und 95 â¬ lag.

Meine Kundennummer ist 5847-3290 und der aktuelle ZÃ¤hlerstand 28475 kWh. Mein Verbrauch hat sich in den letzten Monaten nicht verÃ¤ndert â wir sind weiterhin zu dritt im Haushalt, ohne neue GerÃ¤te. Eine Verdreifachung der Rechnung ist nicht nachvollziehbar.

Bitte Ã¼berprÃ¼fen Sie den ZÃ¤hler vor Ort und stellen Sie sicher, dass kein Ablesefehler vorliegt. Bis zur endgÃ¼ltigen KlÃ¤rung bitte ich Sie, die SEPA-Abbuchung auszusetzen.

Ich erwarte Ihre schriftliche Antwort innerhalb von 14 Tagen.

Mit freundlichen GrÃ¼Ãen,
Ahmad Halabi`},{id:`schreiben-11-2`,taskNumber:2,typeAr:`Ø·ÙØ¨ ÙÙØ¹Ø¯ ÙØ¯Ù Ø§ÙØ·Ø¨ÙØ¨`,typeDe:`Terminanfrage beim Arzt`,promptAr:`ØªØ¹Ø§ÙÙ ÙÙ Ø£ÙÙ ÙÙ Ø§ÙØ¸ÙØ± ÙÙØ° Ø£Ø³Ø¨ÙØ¹. Ø§ÙØªØ¨ Ø¨Ø±ÙØ¯Ø§Ù ÙØ¹ÙØ§Ø¯Ø© Ø§ÙØ·Ø¨ÙØ¨ ÙØ·ÙØ¨ ÙÙØ¹Ø¯ Ø¹Ø§Ø¬Ù.`,promptDe:`Sie haben seit einer Woche RÃ¼ckenschmerzen. Schreiben Sie eine E-Mail an die Arztpraxis, um einen dringenden Termin zu bekommen.`,requirements:[`Ø§Ø°ÙØ± Ø§Ø³ÙÙ ÙØªØ§Ø±ÙØ® ÙÙÙØ§Ø¯Ù`,`ØµÙ Ø§ÙØ£Ø¹Ø±Ø§Ø¶`,`Ø§ÙØªØ±Ø­ ÙÙØ¹Ø¯Ø§Ù (ÙØ¹ Ø¨Ø¯Ø§Ø¦Ù)`,`Ø§Ø°ÙØ± Ø´Ø±ÙØ© Ø§ÙØªØ£ÙÙÙ`],wordCount:`Ø­ÙØ§ÙÙ 80 ÙÙÙØ©`,usefulPhrases:[{de:`Sehr geehrtes Praxisteam,`,ar:`ÙØ±ÙÙ Ø§ÙØ¹ÙØ§Ø¯Ø© Ø§ÙÙØ­ØªØ±ÙØ`},{de:`mein Name ist ..., geboren am ...`,ar:`Ø§Ø³ÙÙ... ÙÙÙÙØ¯ ÙÙ...`},{de:`Ich leide seit ... an starken Schmerzen.`,ar:`Ø£Ø¹Ø§ÙÙ ÙÙØ°... ÙÙ Ø£ÙÙ Ø´Ø¯ÙØ¯.`},{de:`Ich bitte um einen baldigen Termin.`,ar:`Ø£Ø±Ø¬Ù ÙÙØ¹Ø¯Ø§Ù ÙØ±ÙØ¨Ø§Ù.`},{de:`Ich kann Montag bis Freitag ab 16 Uhr kommen.`,ar:`Ø£Ø³ØªØ·ÙØ¹ ÙÙ Ø§ÙØ¥Ø«ÙÙÙ ÙÙØ¬ÙØ¹Ø© Ø¨Ø¹Ø¯ Ø§ÙÙ16.`},{de:`Meine Krankenkasse ist ...`,ar:`ØªØ£ÙÙÙÙ Ø§ÙØµØ­Ù ÙÙ...`}],sampleAnswer:`Sehr geehrtes Praxisteam Dr. Wagner,

mein Name ist Salah Karim, geboren am 12.05.1985. Ich bin Ihr Patient seit 2022.

Ich leide seit einer Woche an starken RÃ¼ckenschmerzen, besonders im unteren Bereich. Auch das Aufstehen morgens fÃ¤llt mir sehr schwer. Schmerztabletten helfen kaum noch.

Ich bitte daher um einen baldigen Termin, am besten in dieser oder nÃ¤chsten Woche. Ich kann Montag bis Freitag ab 16 Uhr und samstags vormittags kommen.

Meine Krankenkasse ist die AOK.

Vielen Dank im Voraus fÃ¼r Ihre MÃ¼he!

Mit freundlichen GrÃ¼Ãen,
Salah Karim`},{id:`schreiben-11-3`,taskNumber:3,typeAr:`Ø±ÙØ¶ Ø¯Ø¹ÙØ© Ø¨Ø£Ø¯Ø¨`,typeDe:`HÃ¶fliche Absage einer Einladung`,promptAr:`Ø¯Ø¹ØªÙ Ø¬Ø§Ø±ØªÙ Ø§ÙØ³ÙÙØ¯Ø© Ø´ÙÙØ¯Øª ÙØ­ÙÙØ© Ø¹ÙØ¯ ÙÙÙØ§Ø¯ Ø§Ø¨ÙØªÙØ§. ÙØ§ ØªØ³ØªØ·ÙØ¹ Ø§ÙØ­Ø¶ÙØ±. Ø§ÙØªØ¨ Ø±Ø³Ø§ÙØ© ÙØµÙØ±Ø©.`,promptDe:`Ihre Nachbarin Frau Schmidt hat Sie zur Geburtstagsfeier ihrer Tochter eingeladen. Sie kÃ¶nnen nicht kommen. Schreiben Sie eine kurze E-Mail.`,requirements:[`Ø§Ø´ÙØ±ÙØ§ Ø¹ÙÙ Ø§ÙØ¯Ø¹ÙØ©`,`Ø§Ø°ÙØ± Ø§ÙØ³Ø¨Ø¨ Ø¨Ø§Ø®ØªØµØ§Ø±`,`ØªÙÙÙ ÙÙÙØ§Ù Ø¬ÙÙÙØ§Ù`,`Ø§ÙØªØ±Ø­ ÙÙØ¹Ø¯Ø§Ù Ø¨Ø¯ÙÙØ§Ù ÙÙÙØ§Ø¡`],wordCount:`Ø­ÙØ§ÙÙ 60 ÙÙÙØ©`,usefulPhrases:[{de:`Liebe Frau Schmidt,`,ar:`Ø¹Ø²ÙØ²ØªÙ Ø§ÙØ³ÙÙØ¯Ø© Ø´ÙÙØ¯ØªØ`},{de:`vielen Dank fÃ¼r Ihre nette Einladung.`,ar:`Ø´ÙØ±Ø§Ù Ø¬Ø²ÙÙØ§Ù ÙÙØ¯Ø¹ÙØ© Ø§ÙÙØ·ÙÙØ©.`},{de:`leider kann ich nicht kommen, weil ...`,ar:`ÙÙØ£Ø³Ù ÙØ§ Ø£Ø³ØªØ·ÙØ¹ Ø§ÙØ­Ø¶ÙØ± ÙØ£ÙÙ...`},{de:`Ich wÃ¼nsche Ihrer Tochter alles Gute zum Geburtstag.`,ar:`Ø£ØªÙÙÙÙ ÙØ§Ø¨ÙØªÙ ÙÙÙ Ø§ÙØªÙÙÙÙ Ø¨Ø¹ÙØ¯ ÙÙÙØ§Ø¯ÙØ§.`},{de:`KÃ¶nnen wir uns nÃ¤chste Woche auf einen Kaffee treffen?`,ar:`ÙÙ ÙØ³ØªØ·ÙØ¹ Ø§ÙÙÙØ§Ø¡ Ø§ÙØ£Ø³Ø¨ÙØ¹ Ø§ÙÙØ§Ø¯Ù Ø¹ÙÙ ÙÙÙØ©Ø`}],sampleAnswer:`Liebe Frau Schmidt,

vielen Dank fÃ¼r Ihre nette Einladung zur Geburtstagsfeier von Mia. Leider kann ich nicht kommen, weil ich an diesem Wochenende eine Pflicht-Veranstaltung an der UniversitÃ¤t habe, die ich nicht verschieben kann.

Bitte richten Sie Mia meine herzlichen GlÃ¼ckwÃ¼nsche aus! Ich werde ihr ein kleines Geschenk vor die TÃ¼r stellen.

Vielleicht kÃ¶nnen wir uns nÃ¤chste Woche auf einen Kaffee treffen? Donnerstag oder Freitag Nachmittag wÃ¼rde mir passen.

Liebe GrÃ¼Ãe,
Lina`}]}];export{e as t};
